export const en = {
  "badge.agentNeedsYou": "Needs attention",
  "badge.agentStopped": "Agent stopped",
  "badge.agentWorking": "Agent working",
  "badge.blocked": "Blocked",
  "badge.blockedHint": "Waiting on open tasks",
  "badge.cycleEmpty": "Some tasks block each other; untangle them in the tracker.",
  "badge.cycleHint": "These tasks block each other; untangle them in the tracker.",
  "badge.cycleLoop": "Blocking each other: {{loop}}",
  "badge.externalRef": "In another repository — open it from the issue page.",
  "badge.focusSession": "Focus the session",
  "badge.focusSessionAria": "Focus the session for this task",
  "badge.inCycle": "In cycle",
  "badge.prMerged": "PR merged",
  "badge.ready": "Ready",
  "badge.waitingOn": "Waiting on {{count}} open tasks",
  "badge.waitingOnKeys": "Waiting on {{keys}}",
  "badge.workingTree": "Working tree",
  "column.done": "Done",
  "column.inProgress": "In Progress",
  "column.todo": "Todo",
  "dag.cycle": "Dependency cycle",
  "dag.done": "Done",
  "dag.inProgress": "In Progress",
  "dag.ready": "Ready to start",
  "dag.waiting": "Waiting on blockers",
  "dag.waitingSteps": "Waiting on blockers · {{n}} steps away",
  "edge.blockedBy": "blocked by",
  "edge.blocks": "blocks",
  "edge.cycleWith": "cycle with",
  "edge.jumpTo": "Jump to {{key}}",
  "edge.openIssue": "Open {{key}} in the tracker",
  "menu.actions": "Task actions",
  "menu.closeInTracker": "Close in tracker",
  "menu.copyLink": "Copy link",
  "menu.focusSession": "Focus session",
  "menu.moveHint": "Updates the issue in the tracker",
  "menu.moveTo": "Move to {{column}}",
  "menu.moveToDone": "Move to Done",
  "menu.moveToDoneHint": "Waits for linked PRs to merge",
  "menu.pruneWorktree": "Clean up working tree",
  "menu.startWork": "Start work",
  "menu.startWorkHint": "Starts an agent in a new working tree",
  "menu.viewInTracker": "View in tracker",
  "view.boardTitle": "Board",
  "view.columnsAssignment": "Columns from assignment",
  "view.columnsHint":
    "Column mapping comes from the tracker: assignment by default, project columns when a Projects board is bound.",
  "view.columnsProject": "Columns from project",
  "view.emptyBody":
    "Create an issue in the tracker. Then start work from a card — Pier opens a working tree and an agent.",
  "view.emptyColumn": "No tasks",
  "view.emptyFilter": "No tasks in this filter yet.",
  "view.emptyTitle": "No issues yet",
  "view.graphCaption": "Blockers sit above the tasks they block.",
  "view.graphExperimental": "Experimental",
  "view.graphExperimentalHint":
    "Layout may change; the board and list are the stable views.",
  "view.graphOverBudget":
    "Too many crossing blockers for a stable graph. Use the board or list.",
  "view.graphTitle": "Task graph",
  "view.listTitle": "Task list",
  "view.loadBoardFailed": "Couldn’t load the board",
  "view.loadBoardHint": "Retry. If authorization expired, reconnect from this panel.",
  "view.loadGraphFailed": "Couldn’t load the graph",
  "view.loadListFailed": "Couldn’t update the list",
  "view.loadingBoard": "Loading board…",
  "view.moveFailed": "Couldn’t move that card.",
  "view.moveSelected": "Move selected",
  "view.readOnly": "Read-only",
  "view.reconnect": "Reconnect",
  "view.readOnlyHint":
    "Your tracker account doesn’t have write access to this repository.",
  "view.refresh": "Refresh",
  "view.repoHint": "Issues load from this tracker repository.",
  "view.retry": "Retry",
  "view.selectCard": "Select {{key}}",
  "view.selected": "{{count}} selected",
  "view.startReady": "Start ready tasks",
  "view.startReadyHint":
    "Creates a working tree and starts an agent for each ready task.",
  "view.startReadyMany": "Start {{count}} ready tasks",
  "view.startReadyOne": "Start 1 ready task",
  "view.truncated": "Showing the first 100 issues",
  "view.truncatedHint":
    "Showing the first 100 issues. Open a named canvas for a smaller set.",
  "view.updated": "Updated {{time}}",
} as const;
