import type { en } from "./en.ts";

export const ja: { [K in keyof typeof en]: string } = {
  "badge.agentNeedsYou": "エージェントの対応が必要",
  "badge.agentStopped": "エージェントが停止しました",
  "badge.agentWorking": "エージェント作業中",
  "badge.blocked": "ブロック中",
  "badge.blockedHint": "未完了のタスクを待っています",
  "badge.cycleEmpty": "互いにブロックしているタスクがあります。トラッカーで解消してください。",
  "badge.cycleHint": "これらのタスクは互いにブロックしています。トラッカーで解消してください。",
  "badge.cycleLoop": "相互ブロック: {{loop}}",
  "badge.externalRef": "別リポジトリにあります。課題ページから開いてください。",
  "badge.focusSession": "セッションにフォーカス",
  "badge.focusSessionAria": "このタスクのセッションにフォーカス",
  "badge.inCycle": "循環依存",
  "badge.prMerged": "PR マージ済み",
  "badge.ready": "開始可",
  "badge.waitingOn": "未完了タスク {{count}} 件を待機",
  "badge.waitingOnKeys": "{{keys}} を待機",
  "badge.workingTree": "作業ツリー",
  "column.done": "完了",
  "column.inProgress": "進行中",
  "column.todo": "未着手",
  "dag.cycle": "循環依存",
  "dag.done": "完了",
  "dag.inProgress": "進行中",
  "dag.ready": "開始可",
  "dag.waiting": "ブロッカー待ち",
  "dag.waitingSteps": "ブロッカー待ち · あと {{n}} 段",
  "edge.blockedBy": "ブロック元",
  "edge.blocks": "ブロック先",
  "edge.cycleWith": "循環",
  "edge.jumpTo": "{{key}} へ移動",
  "edge.openIssue": "トラッカーで {{key}} を開く",
  "menu.actions": "タスク操作",
  "menu.closeInTracker": "トラッカーでクローズ",
  "menu.copyLink": "リンクをコピー",
  "menu.focusSession": "セッションにフォーカス",
  "menu.moveHint": "トラッカー上の課題を更新します",
  "menu.moveTo": "{{column}} へ移動",
  "menu.moveToDone": "完了へ移動",
  "menu.moveToDoneHint": "リンクされた PR のマージ後に移動できます",
  "menu.pruneWorktree": "作業ツリーを片付ける",
  "menu.startWork": "作業を開始",
  "menu.startWorkHint": "新しい作業ツリーでエージェントを起動します",
  "menu.viewInTracker": "トラッカーで表示",
  "view.boardTitle": "ボード",
  "view.columnsAssignment": "担当で列分け",
  "view.columnsHint":
    "列の対応はトラッカー側です。既定は担当、Projects ボードをバインドするとプロジェクト列です。",
  "view.columnsProject": "プロジェクト列で列分け",
  "view.emptyBody":
    "トラッカーで課題を作成してください。カードから作業を開始すると、Pier が作業ツリーとエージェントを開きます。",
  "view.emptyColumn": "タスクなし",
  "view.emptyFilter": "このフィルタにはまだタスクがありません。",
  "view.emptyTitle": "課題はまだありません",
  "view.graphCaption": "ブロッカーはブロックされているタスクの上にあります。",
  "view.graphExperimental": "実験的",
  "view.graphExperimentalHint": "レイアウトは変わることがあります。安定したビューはボードとリストです。",
  "view.graphOverBudget": "交差するブロックが多すぎます。ボードまたはリストを使ってください。",
  "view.graphTitle": "依存グラフ",
  "view.listTitle": "リスト",
  "view.loadBoardFailed": "ボードを読み込めませんでした",
  "view.loadBoardHint": "再試行してください。認可の期限が切れている場合は、このパネルから再接続します。",
  "view.loadGraphFailed": "グラフを読み込めませんでした",
  "view.loadListFailed": "リストを更新できませんでした",
  "view.loadingBoard": "ボードを読み込み中…",
  "view.moveFailed": "そのカードを移動できませんでした。",
  "view.moveSelected": "選択を移動",
  "view.readOnly": "読み取り専用",
  "view.reconnect": "再接続",
  "view.readOnlyHint": "このトラッカーアカウントにはリポジトリの書き込み権限がありません。",
  "view.refresh": "更新",
  "view.repoHint": "課題はこのトラッカーリポジトリから読みます。",
  "view.retry": "再試行",
  "view.selectCard": "{{key}} を選択",
  "view.selected": "{{count}} 件選択",
  "view.startReady": "開始可能なタスクを開始",
  "view.startReadyHint": "開始可能な各タスクの作業ツリーを作り、エージェントを起動します。",
  "view.startReadyMany": "開始可能なタスク {{count}} 件を開始",
  "view.startReadyOne": "開始可能なタスク 1 件を開始",
  "view.truncated": "先頭 100 件のみ表示",
  "view.truncatedHint":
    "先頭 100 件のみ表示しています。範囲を絞ったキャンバスを開いてください。",
  "view.updated": "{{time}}に更新",
};
