import type { en } from "./en.ts";

export const ko: { [K in keyof typeof en]: string } = {
  "badge.agentNeedsYou": "에이전트 처리 필요",
  "badge.agentStopped": "에이전트가 멈춤",
  "badge.agentWorking": "에이전트 작업 중",
  "badge.blocked": "막힘",
  "badge.blockedHint": "끝나지 않은 작업을 기다리는 중",
  "badge.cycleEmpty": "서로 막고 있는 작업이 있습니다. 트래커에서 풀어 주세요.",
  "badge.cycleHint": "이 작업들이 서로를 막고 있습니다. 트래커에서 풀어 주세요.",
  "badge.cycleLoop": "서로 막힘: {{loop}}",
  "badge.externalRef": "다른 저장소에 있습니다. 이슈 페이지에서 여세요.",
  "badge.focusSession": "세션으로 이동",
  "badge.focusSessionAria": "이 작업의 세션으로 이동",
  "badge.inCycle": "순환 의존",
  "badge.prMerged": "PR 병합됨",
  "badge.ready": "시작 가능",
  "badge.waitingOn": "미완료 작업 {{count}}개 대기",
  "badge.waitingOnKeys": "{{keys}} 대기",
  "badge.workingTree": "작업 트리",
  "column.done": "완료",
  "column.inProgress": "진행 중",
  "column.todo": "할 일",
  "dag.cycle": "순환 의존",
  "dag.done": "완료",
  "dag.inProgress": "진행 중",
  "dag.ready": "시작 가능",
  "dag.waiting": "막는 항목 대기",
  "dag.waitingSteps": "막는 항목 대기 · {{n}}단계 남음",
  "edge.blockedBy": "막힘",
  "edge.blocks": "막음",
  "edge.cycleWith": "순환",
  "edge.jumpTo": "{{key}}(으)로 이동",
  "edge.openIssue": "트래커에서 {{key}} 열기",
  "menu.actions": "작업 동작",
  "menu.closeInTracker": "트래커에서 닫기",
  "menu.copyLink": "링크 복사",
  "menu.focusSession": "세션으로 이동",
  "menu.moveHint": "트래커에서 이슈를 업데이트합니다",
  "menu.moveTo": "{{column}}(으)로 이동",
  "menu.moveToDone": "완료로 이동",
  "menu.moveToDoneHint": "연결된 PR이 병합된 뒤에 이동합니다",
  "menu.pruneWorktree": "작업 트리 정리",
  "menu.startWork": "작업 시작",
  "menu.startWorkHint": "새 작업 트리에서 에이전트를 시작합니다",
  "menu.viewInTracker": "트래커에서 보기",
  "view.boardTitle": "보드",
  "view.columnsAssignment": "담당자로 열 구분",
  "view.columnsHint":
    "열 매핑은 트래커를 따릅니다. 기본은 담당자이고, Projects 보드를 연결하면 프로젝트 열입니다.",
  "view.columnsProject": "프로젝트 열로 구분",
  "view.emptyBody":
    "트래커에서 이슈를 만드세요. 카드에서 작업을 시작하면 Pier가 작업 트리와 에이전트를 엽니다.",
  "view.emptyColumn": "작업 없음",
  "view.emptyFilter": "이 필터에는 아직 작업이 없습니다.",
  "view.emptyTitle": "아직 이슈가 없습니다",
  "view.graphCaption": "막는 항목이 막힌 작업 위에 있습니다.",
  "view.graphExperimental": "실험적",
  "view.graphExperimentalHint": "레이아웃이 바뀔 수 있습니다. 안정 뷰는 보드와 목록입니다.",
  "view.graphOverBudget": "교차하는 막힘이 너무 많습니다. 보드나 목록을 쓰세요.",
  "view.graphTitle": "의존 그래프",
  "view.listTitle": "목록",
  "view.loadBoardFailed": "보드를 불러오지 못했습니다",
  "view.loadBoardHint": "다시 시도하세요. 권한이 만료되었다면 이 패널에서 다시 연결하세요.",
  "view.loadGraphFailed": "그래프를 불러오지 못했습니다",
  "view.loadListFailed": "목록을 업데이트하지 못했습니다",
  "view.loadingBoard": "보드 불러오는 중…",
  "view.moveFailed": "카드를 옮기지 못했습니다.",
  "view.moveSelected": "선택 항목 이동",
  "view.readOnly": "읽기 전용",
  "view.reconnect": "다시 연결",
  "view.readOnlyHint": "이 트래커 계정에는 저장소 쓰기 권한이 없습니다.",
  "view.refresh": "새로고침",
  "view.repoHint": "이슈는 이 트래커 저장소에서 불러옵니다.",
  "view.retry": "다시 시도",
  "view.selectCard": "{{key}} 선택",
  "view.selected": "{{count}}개 선택됨",
  "view.startReady": "시작 가능한 작업 시작",
  "view.startReadyHint": "시작 가능한 각 작업의 작업 트리를 만들고 에이전트를 시작합니다.",
  "view.startReadyMany": "시작 가능한 작업 {{count}}개 시작",
  "view.startReadyOne": "시작 가능한 작업 1개 시작",
  "view.truncated": "처음 100개만 표시",
  "view.truncatedHint":
    "처음 100개만 표시합니다. 범위가 더 작은 캔버스를 여세요.",
  "view.updated": "{{time}} 업데이트",
};
