import type { en } from "./en.ts";

export const zhCN: { [K in keyof typeof en]: string } = {
  "badge.agentNeedsYou": "智能体需要你处理",
  "badge.agentStopped": "智能体已停止",
  "badge.agentWorking": "智能体工作中",
  "badge.blocked": "被阻塞",
  "badge.blockedHint": "在等待未完成的任务",
  "badge.cycleEmpty": "有任务互相阻塞，请到跟踪器里解开。",
  "badge.cycleHint": "这些任务互相阻塞，请到跟踪器里解开。",
  "badge.cycleLoop": "互相阻塞：{{loop}}",
  "badge.externalRef": "在另一个仓库中 — 请从议题页打开。",
  "badge.focusSession": "聚焦会话",
  "badge.focusSessionAria": "聚焦此任务的会话",
  "badge.inCycle": "循环依赖",
  "badge.prMerged": "PR 已合并",
  "badge.ready": "可开始",
  "badge.waitingOn": "等待 {{count}} 个未完成任务",
  "badge.waitingOnKeys": "等待 {{keys}}",
  "badge.workingTree": "工作树",
  "column.done": "已完成",
  "column.inProgress": "进行中",
  "column.todo": "待办",
  "dag.cycle": "循环依赖",
  "dag.done": "已完成",
  "dag.inProgress": "进行中",
  "dag.ready": "可开始",
  "dag.waiting": "等待阻塞项",
  "dag.waitingSteps": "等待阻塞项 · 还差 {{n}} 步",
  "edge.blockedBy": "被阻塞于",
  "edge.blocks": "阻塞",
  "edge.cycleWith": "循环于",
  "edge.jumpTo": "跳到 {{key}}",
  "edge.openIssue": "在跟踪器中打开 {{key}}",
  "menu.actions": "任务操作",
  "menu.closeInTracker": "在跟踪器中关闭",
  "menu.copyLink": "复制链接",
  "menu.focusSession": "聚焦会话",
  "menu.moveHint": "在跟踪器中更新此议题",
  "menu.moveTo": "移动到{{column}}",
  "menu.moveToDone": "移动到已完成",
  "menu.moveToDoneHint": "等关联 PR 合并后再移动",
  "menu.pruneWorktree": "清理工作树",
  "menu.startWork": "开始工作",
  "menu.startWorkHint": "在新的工作树中启动智能体",
  "menu.viewInTracker": "在跟踪器中查看",
  "view.boardTitle": "看板",
  "view.columnsAssignment": "按指派分列",
  "view.columnsHint":
    "列映射来自跟踪器：默认按指派，绑定 Projects 看板后按项目列。",
  "view.columnsProject": "按项目列分列",
  "view.emptyBody":
    "请先在跟踪器里创建议题。然后在卡片上开始工作 — Pier 会打开工作树并启动智能体。",
  "view.emptyColumn": "没有任务",
  "view.emptyFilter": "此筛选下还没有任务。",
  "view.emptyTitle": "还没有议题",
  "view.graphCaption": "阻塞方显示在被阻塞任务的上方。",
  "view.graphExperimental": "实验性",
  "view.graphExperimentalHint": "布局可能变化；看板和列表是稳定视图。",
  "view.graphOverBudget": "交叉阻塞过多，图不稳定。请改用看板或列表。",
  "view.graphTitle": "依赖图",
  "view.listTitle": "列表",
  "view.loadBoardFailed": "无法加载看板",
  "view.loadBoardHint": "请重试。如果授权已失效，请在此面板重新连接。",
  "view.loadGraphFailed": "无法加载依赖图",
  "view.loadListFailed": "无法更新列表",
  "view.loadingBoard": "正在加载看板…",
  "view.moveFailed": "无法移动这张卡片。",
  "view.moveSelected": "移动所选",
  "view.readOnly": "只读",
  "view.reconnect": "重新连接",
  "view.readOnlyHint": "当前跟踪器账号没有此仓库的写入权限。",
  "view.refresh": "刷新",
  "view.repoHint": "议题来自该跟踪器仓库。",
  "view.retry": "重试",
  "view.selectCard": "选择 {{key}}",
  "view.selected": "已选 {{count}} 项",
  "view.startReady": "开始可做的任务",
  "view.startReadyHint": "为每个可开始的任务创建工作树并启动智能体。",
  "view.startReadyMany": "开始 {{count}} 个可做的任务",
  "view.startReadyOne": "开始 1 个可做的任务",
  "view.truncated": "只显示前 100 条",
  "view.truncatedHint": "只显示前 100 条。打开一份范围更小的画布可以缩小集合。",
  "view.updated": "更新于 {{time}}",
};
