import type { ComponentType, CSSProperties, ReactNode } from "react";

/**
 * Shared declaration for standard shadcn-style primitives. These components
 * follow their normal composition contracts: triggers live under roots,
 * items live under groups/lists, and form controls use standard DOM props.
 *
 * Complex Pier-specific APIs are declared precisely in the sibling files.
 */
export interface CanvasPrimitiveProps {
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
  [prop: string]: unknown;
}

export type CanvasPrimitive = ComponentType<CanvasPrimitiveProps>;

export const Accordion: CanvasPrimitive;
export const AccordionContent: CanvasPrimitive;
export const AccordionItem: CanvasPrimitive;
export const AccordionTrigger: CanvasPrimitive;
export const Alert: CanvasPrimitive;
export const AlertAction: CanvasPrimitive;
export const AlertDescription: CanvasPrimitive;
export const AlertTitle: CanvasPrimitive;
export const AspectRatio: CanvasPrimitive;
export const Avatar: CanvasPrimitive;
export const AvatarBadge: CanvasPrimitive;
export const AvatarFallback: CanvasPrimitive;
export const AvatarGroup: CanvasPrimitive;
export const AvatarGroupCount: CanvasPrimitive;
export const AvatarImage: CanvasPrimitive;
export const Badge: CanvasPrimitive;
export const Breadcrumb: CanvasPrimitive;
export const BreadcrumbEllipsis: CanvasPrimitive;
export const BreadcrumbItem: CanvasPrimitive;
export const BreadcrumbLink: CanvasPrimitive;
export const BreadcrumbList: CanvasPrimitive;
export const BreadcrumbPage: CanvasPrimitive;
export const BreadcrumbSeparator: CanvasPrimitive;
export const Card: CanvasPrimitive;
export const CardContent: CanvasPrimitive;
export const CardDescription: CanvasPrimitive;
export const CardHeader: CanvasPrimitive;
export const CardTitle: CanvasPrimitive;
export const Collapsible: CanvasPrimitive;
export const CollapsibleContent: CanvasPrimitive;
export const CollapsibleTrigger: CanvasPrimitive;
export const DropdownMenu: CanvasPrimitive;
export const DropdownMenuCheckboxItem: CanvasPrimitive;
export const DropdownMenuContent: CanvasPrimitive;
export const DropdownMenuGroup: CanvasPrimitive;
export const DropdownMenuItem: CanvasPrimitive;
export const DropdownMenuLabel: CanvasPrimitive;
export const DropdownMenuPortal: CanvasPrimitive;
export const DropdownMenuRadioGroup: CanvasPrimitive;
export const DropdownMenuRadioItem: CanvasPrimitive;
export const DropdownMenuSeparator: CanvasPrimitive;
export const DropdownMenuShortcut: CanvasPrimitive;
export const DropdownMenuSub: CanvasPrimitive;
export const DropdownMenuSubContent: CanvasPrimitive;
export const DropdownMenuSubTrigger: CanvasPrimitive;
export const DropdownMenuTrigger: CanvasPrimitive;
export const Empty: CanvasPrimitive;
export const EmptyContent: CanvasPrimitive;
export const EmptyDescription: CanvasPrimitive;
export const EmptyHeader: CanvasPrimitive;
export const EmptyMedia: CanvasPrimitive;
export const EmptyTitle: CanvasPrimitive;
export const Field: CanvasPrimitive;
export const FieldContent: CanvasPrimitive;
export const FieldDescription: CanvasPrimitive;
export const FieldError: CanvasPrimitive;
export const FieldGroup: CanvasPrimitive;
export const FieldLabel: CanvasPrimitive;
export const FieldLegend: CanvasPrimitive;
export const FieldSeparator: CanvasPrimitive;
export const FieldSet: CanvasPrimitive;
export const FieldTitle: CanvasPrimitive;
export const HoverCard: CanvasPrimitive;
export const HoverCardContent: CanvasPrimitive;
export const HoverCardTrigger: CanvasPrimitive;
export const InputGroup: CanvasPrimitive;
export const InputGroupAddon: CanvasPrimitive;
export const InputGroupButton: CanvasPrimitive;
export const InputGroupInput: CanvasPrimitive;
export const InputGroupText: CanvasPrimitive;
export const InputGroupTextarea: CanvasPrimitive;
export const Item: CanvasPrimitive;
export const ItemActions: CanvasPrimitive;
export const ItemContent: CanvasPrimitive;
export const ItemDescription: CanvasPrimitive;
export const ItemFooter: CanvasPrimitive;
export const ItemGroup: CanvasPrimitive;
export const ItemHeader: CanvasPrimitive;
export const ItemMedia: CanvasPrimitive;
export const ItemSeparator: CanvasPrimitive;
export const ItemTitle: CanvasPrimitive;
export const Kbd: CanvasPrimitive;
export const KbdGroup: CanvasPrimitive;
export const Pagination: CanvasPrimitive;
export const PaginationContent: CanvasPrimitive;
export const PaginationEllipsis: CanvasPrimitive;
export const PaginationItem: CanvasPrimitive;
export const PaginationLink: CanvasPrimitive;
export const PaginationNext: CanvasPrimitive;
export const PaginationPrevious: CanvasPrimitive;
export const Popover: CanvasPrimitive;
export const PopoverAnchor: CanvasPrimitive;
export const PopoverContent: CanvasPrimitive;
export const PopoverDescription: CanvasPrimitive;
export const PopoverHeader: CanvasPrimitive;
export const PopoverTitle: CanvasPrimitive;
export const PopoverTrigger: CanvasPrimitive;
export const Progress: CanvasPrimitive;
export const ScrollArea: CanvasPrimitive;
export const ScrollBar: CanvasPrimitive;
export const Separator: CanvasPrimitive;
export const Skeleton: CanvasPrimitive;
export const Spinner: CanvasPrimitive;
export const StatusIcon: CanvasPrimitive;
export const Table: CanvasPrimitive;
export const TableBody: CanvasPrimitive;
export const TableCaption: CanvasPrimitive;
export const TableCell: CanvasPrimitive;
export const TableFooter: CanvasPrimitive;
export const TableHead: CanvasPrimitive;
export const TableHeader: CanvasPrimitive;
export const TableRow: CanvasPrimitive;
export const Tabs: CanvasPrimitive;
export const TabsContent: CanvasPrimitive;
export const TabsList: CanvasPrimitive;
export const TabsTrigger: CanvasPrimitive;
export const Tooltip: CanvasPrimitive;
export const TooltipContent: CanvasPrimitive;
export const TooltipProvider: CanvasPrimitive;
export const TooltipTrigger: CanvasPrimitive;
