import type { PluginManifest } from "@shared/contracts/plugin.ts";
import {
  FILES_COPY_PATH_COMMAND_ID,
  FILES_COPY_PATH_WITH_RANGE_COMMAND_ID,
  FILES_COPY_RELATIVE_PATH_COMMAND_ID,
  FILES_DELETE_COMMAND_ID,
  FILES_DUPLICATE_COMMAND_ID,
  FILES_EDITOR_COPY_COMMAND_ID,
  FILES_EDITOR_CUT_COMMAND_ID,
  FILES_EDITOR_GO_TO_LINE_COMMAND_ID,
  FILES_EDITOR_PASTE_COMMAND_ID,
  FILES_EDITOR_SELECT_ALL_COMMAND_ID,
  FILES_EDITOR_SHOW_HOVER_COMMAND_ID,
  FILES_FILE_CLIPBOARD_COPY_COMMAND_ID,
  FILES_FILE_CLIPBOARD_CUT_COMMAND_ID,
  FILES_FILE_CLIPBOARD_PASTE_COMMAND_ID,
  FILES_MARKDOWN_APPEARANCE_AUTO_COMMAND_ID,
  FILES_MARKDOWN_APPEARANCE_DARK_COMMAND_ID,
  FILES_MARKDOWN_APPEARANCE_LIGHT_COMMAND_ID,
  FILES_MARKDOWN_MEASURE_COMFORTABLE_COMMAND_ID,
  FILES_MARKDOWN_MEASURE_WIDE_COMMAND_ID,
  FILES_NEW_FILE_COMMAND_ID,
  FILES_NEW_FOLDER_COMMAND_ID,
  FILES_OPEN_DIRECTORY_COMMAND_ID,
  FILES_QUICK_OPEN_COMMAND_ID,
  FILES_RENAME_COMMAND_ID,
  FILES_REVEAL_ACTIVE_IN_TREE_COMMAND_ID,
  FILES_REVEAL_COMMAND_ID,
  FILES_SAVE_ALL_COMMAND_ID,
  FILES_SAVE_AS_COMMAND_ID,
  FILES_SAVE_COMMAND_ID,
  FILES_SEARCH_CONTENTS_COMMAND_ID,
  FILES_SEARCH_COPY_MATCH_COMMAND_ID,
  FILES_SEARCH_COPY_PATH_COMMAND_ID,
  FILES_SEARCH_COPY_RELATIVE_PATH_COMMAND_ID,
  FILES_SEARCH_IN_FOLDER_COMMAND_ID,
  FILES_SEARCH_OPEN_HIT_COMMAND_ID,
  FILES_SEARCH_REVEAL_COMMAND_ID,
  FILES_TREE_COLLAPSE_FOLDERS_COMMAND_ID,
  FILES_TREE_EXPAND_ALL_COMMAND_ID,
  FILES_TREE_SEARCH_COMMAND_ID,
} from "./command-ids.ts";

export const FILES_PLUGIN_COMMANDS: PluginManifest["commands"] = [
  {
    category: "file",
    id: FILES_NEW_FILE_COMMAND_ID,
    permissions: ["file:read", "file:write", "panel:open"],
    title: "New File...",
  },
  {
    category: "file",
    id: FILES_NEW_FOLDER_COMMAND_ID,
    permissions: ["file:read", "file:write", "panel:open"],
    title: "New Folder...",
  },
  {
    category: "file",
    id: FILES_RENAME_COMMAND_ID,
    permissions: ["file:read", "file:write"],
    title: "Rename...",
  },
  {
    category: "file",
    id: FILES_DELETE_COMMAND_ID,
    permissions: ["file:write"],
    title: "Delete",
  },
  {
    category: "file",
    id: FILES_COPY_PATH_COMMAND_ID,
    permissions: [],
    title: "Copy Path",
  },
  {
    category: "file",
    id: FILES_COPY_RELATIVE_PATH_COMMAND_ID,
    permissions: [],
    title: "Copy Relative Path",
  },
  {
    category: "file",
    id: FILES_COPY_PATH_WITH_RANGE_COMMAND_ID,
    permissions: [],
    title: "Copy Path and Selected Lines",
  },
  {
    category: "file",
    id: FILES_SAVE_COMMAND_ID,
    permissions: ["file:write"],
    title: "Save",
  },
  {
    category: "file",
    id: FILES_SAVE_AS_COMMAND_ID,
    permissions: ["file:write"],
    title: "Save As...",
  },
  {
    category: "file",
    id: FILES_SAVE_ALL_COMMAND_ID,
    permissions: ["file:write"],
    title: "Save All",
  },
  {
    category: "file",
    id: FILES_REVEAL_COMMAND_ID,
    permissions: ["file:read"],
    title: "Reveal in Finder",
  },
  {
    category: "file",
    id: FILES_DUPLICATE_COMMAND_ID,
    permissions: ["file:read", "file:write"],
    title: "Duplicate",
  },
  {
    category: "file",
    id: FILES_FILE_CLIPBOARD_CUT_COMMAND_ID,
    permissions: ["file:read", "file:write"],
    title: "Cut",
  },
  {
    category: "file",
    id: FILES_FILE_CLIPBOARD_COPY_COMMAND_ID,
    // copy 仅写内存剪贴板；落盘在 paste。
    permissions: ["file:read"],
    title: "Copy",
  },
  {
    category: "file",
    id: FILES_FILE_CLIPBOARD_PASTE_COMMAND_ID,
    permissions: ["file:read", "file:write"],
    title: "Paste",
  },
  {
    category: "file",
    id: FILES_SEARCH_OPEN_HIT_COMMAND_ID,
    permissions: ["file:read", "panel:open"],
    title: "Open Search Result",
  },
  {
    category: "file",
    id: FILES_SEARCH_COPY_PATH_COMMAND_ID,
    permissions: ["file:read"],
    title: "Copy Path",
  },
  {
    category: "file",
    id: FILES_SEARCH_COPY_RELATIVE_PATH_COMMAND_ID,
    permissions: ["file:read"],
    title: "Copy Relative Path",
  },
  {
    category: "file",
    id: FILES_SEARCH_COPY_MATCH_COMMAND_ID,
    permissions: ["file:read"],
    title: "Copy Match Line",
  },
  {
    category: "file",
    id: FILES_SEARCH_REVEAL_COMMAND_ID,
    permissions: ["file:read"],
    title: "Reveal in Finder",
  },
  {
    category: "file",
    id: FILES_TREE_SEARCH_COMMAND_ID,
    permissions: [],
    title: "Find in File Tree",
  },
  {
    category: "file",
    id: FILES_REVEAL_ACTIVE_IN_TREE_COMMAND_ID,
    permissions: ["panel:open"],
    title: "Reveal Active File in File Tree",
  },
  {
    category: "file",
    id: FILES_TREE_EXPAND_ALL_COMMAND_ID,
    permissions: [],
    title: "Expand Folders",
  },
  {
    category: "file",
    id: FILES_TREE_COLLAPSE_FOLDERS_COMMAND_ID,
    permissions: [],
    title: "Collapse Folders",
  },
  {
    category: "file",
    id: FILES_QUICK_OPEN_COMMAND_ID,
    permissions: ["file:read", "panel:open"],
    title: "Go to File",
  },
  {
    category: "file",
    id: FILES_OPEN_DIRECTORY_COMMAND_ID,
    permissions: ["file:read", "panel:open"],
    title: "Open Directory",
  },
  {
    category: "file",
    id: FILES_SEARCH_CONTENTS_COMMAND_ID,
    permissions: ["file:read", "panel:open"],
    title: "Search in Files",
  },
  {
    category: "file",
    id: FILES_SEARCH_IN_FOLDER_COMMAND_ID,
    permissions: ["file:read", "panel:open"],
    title: "Find in Folder…",
  },

  {
    category: "file",
    id: FILES_EDITOR_CUT_COMMAND_ID,
    permissions: [],
    title: "Cut",
  },
  {
    category: "file",
    id: FILES_EDITOR_COPY_COMMAND_ID,
    permissions: [],
    title: "Copy",
  },
  {
    category: "file",
    id: FILES_EDITOR_PASTE_COMMAND_ID,
    permissions: [],
    title: "Paste",
  },
  {
    category: "file",
    id: FILES_EDITOR_SELECT_ALL_COMMAND_ID,
    permissions: [],
    title: "Select All",
  },
  {
    category: "file",
    id: FILES_EDITOR_GO_TO_LINE_COMMAND_ID,
    permissions: [],
    title: "Go to Line…",
  },
  {
    category: "file",
    id: FILES_EDITOR_SHOW_HOVER_COMMAND_ID,
    permissions: [],
    title: "Show Symbol Information",
  },
  {
    category: "file",
    id: FILES_MARKDOWN_MEASURE_COMFORTABLE_COMMAND_ID,
    permissions: [],
    title: "Comfortable reading",
  },
  {
    category: "file",
    id: FILES_MARKDOWN_MEASURE_WIDE_COMMAND_ID,
    permissions: [],
    title: "Wide reading",
  },
  {
    category: "file",
    id: FILES_MARKDOWN_APPEARANCE_AUTO_COMMAND_ID,
    permissions: [],
    title: "Match app appearance",
  },
  {
    category: "file",
    id: FILES_MARKDOWN_APPEARANCE_LIGHT_COMMAND_ID,
    permissions: [],
    title: "Light reading",
  },
  {
    category: "file",
    id: FILES_MARKDOWN_APPEARANCE_DARK_COMMAND_ID,
    permissions: [],
    title: "Dark reading",
  },
];
