import { existsSync } from "node:fs";
import { readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import {
  isPierManagedPluginContent,
  pierManagedPluginMarker,
  writeManagedPluginFile,
} from "./managed-plugin-file.ts";
import { JAVASCRIPT_PROMPT_SNIPPET_SOURCE } from "./prompt-snippet-source.ts";
import { commandExistsOnPath } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";
import { JAVASCRIPT_LOCKED_APPEND_SOURCE } from "./writer-lock-source.ts";

const AGENT_ID: AgentKind = "amp";

/** Pier 部署到 amp 自身插件目录下的托管文件（同名同位）。 */
const AMP_PLUGIN_FILE = "pier-agent-status.ts";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const AMP_PLUGIN_MARKER = pierManagedPluginMarker();

/**
 * amp.on 原生事件 → Pier 规范事件名。
 * `agent.end` 的 status 是真实回合结果，必须分支保存，不能压成权威 Stop。
 */
const AMP_EVENT_MAP: ReadonlyArray<{
  nativeEvent: string;
  pierEvent: string;
}> = [
  { nativeEvent: "session.start", pierEvent: "SessionStart" },
  { nativeEvent: "agent.start", pierEvent: "PromptSubmit" },
  { nativeEvent: "thread.state.running", pierEvent: "running" },
  {
    nativeEvent: "thread.state.awaiting-approval",
    pierEvent: "InteractionRequested",
  },
  {
    nativeEvent: "thread.state.running.resolved",
    pierEvent: "InteractionResolved",
  },
  { nativeEvent: "thread.state.idle", pierEvent: "InteractionResolved" },
  {
    nativeEvent: "thread.state.error.resolved",
    pierEvent: "InteractionResolved",
  },
  { nativeEvent: "thread.state.error", pierEvent: "error" },
  { nativeEvent: "agent.end.done", pierEvent: "TurnCompleted" },
  { nativeEvent: "agent.end.error", pierEvent: "error" },
  { nativeEvent: "agent.end.cancelled", pierEvent: "TurnInterrupted" },
];

export function ampPluginPath(): string {
  return join(homedir(), ".config", "amp", "plugins", AMP_PLUGIN_FILE);
}

/**
 * 插件源码是纯字符串模板（不依赖 pierHookCommand/emit 脚本——插件跑在
 * amp 自己的 Node 进程内, 直接写 JSONL）。emit 用
 * `process.getBuiltinModule("node:fs")` 同步 append（同 omp 先例：
 * 同步既保文件序——聚合器按 JSONL 文件序消费, 也保证宿主退出前
 * agent.end 落盘）；旧 Node 宿主退化为异步 best-effort。
 * env 三要素（PIER_AGENT_EVENT_LOG / PIER_PANEL_ID / PIER_WINDOW_ID）任一缺失即
 * 静默 no-op；本地 append 是最佳 effort, 吞异常绝不影响 amp 本体运行。
 */
export function buildAmpPluginSource(): string {
  const eventMapLines = AMP_EVENT_MAP.map(
    (e) => `  "${e.nativeEvent}": "${e.pierEvent}",`
  ).join("\n");
  return `// ${AMP_PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.
// No top-level import declarations: process.getBuiltinModule is a runtime
// call — not an ImportDeclaration; older Node falls back to async best-effort.
// (Exception to ts-no-dynamic-import: generated file for a foreign host.)

const PIER_EVENT_MAP = {
${eventMapLines}
};

${JAVASCRIPT_LOCKED_APPEND_SOURCE}
${JAVASCRIPT_PROMPT_SNIPPET_SOURCE}

function pierSessionIdFrom(values) {
  for (const value of values) {
    if (!value || typeof value !== "object") continue;
    for (const key of ["sessionId", "sessionID", "session_id", "threadId", "threadID", "thread_id"]) {
      if (typeof value[key] === "string" && value[key]) return value[key];
    }
    const session = value.session || value.thread;
    if (session && typeof session === "object") {
      for (const key of ["id", "sessionId", "sessionID", "session_id"]) {
        if (typeof session[key] === "string" && session[key]) return session[key];
      }
    }
  }
  return undefined;
}

function pierFirstString(values, directKeys, nestedKeys) {
  for (const value of values) {
    if (!value || typeof value !== "object") continue;
    for (const key of directKeys) {
      if (typeof value[key] === "string" && value[key]) return value[key];
    }
    for (const nestedKey of nestedKeys) {
      const nested = value[nestedKey];
      if (!nested || typeof nested !== "object") continue;
      if (typeof nested.id === "string" && nested.id) return nested.id;
    }
  }
  return undefined;
}

function emitPierEvent(nativeEvent, ...values) {
  const nativeState = nativeEvent.startsWith("thread.state.")
    ? nativeEvent.split(".")[2]
    : pierFirstString(values, ["status"], []);
  const pierEvent = PIER_EVENT_MAP[nativeEvent];
  if (!pierEvent) return;
  const log = process.env.PIER_AGENT_EVENT_LOG;
  const panelId = process.env.PIER_PANEL_ID;
  const windowId = process.env.PIER_WINDOW_ID;
  if (!log || !panelId || !windowId) return;
  const sessionId = pierSessionIdFrom(values);
  const turnId = pierFirstString(
    values,
    ["id", "turnId", "turnID", "turn_id", "messageId", "messageID", "message_id"],
    []
  );
  const promptSnippet =
    pierEvent === "PromptSubmit" ? pierPromptSnippetFrom(...values) : undefined;
  const line = JSON.stringify({
    v: 3,
    kind: "agentEvent",
    ts: Date.now() * 1_000_000,
    panelId,
    windowId,
    pid: process.pid,
    agent: "amp",
    event: pierEvent,
    nativeEvent,
    ...(sessionId ? { sessionId } : {}),
    ...(turnId ? { turnId } : {}),
    ...(nativeState ? { nativeState } : {}),
    ...(pierEvent === "InteractionRequested" ||
    pierEvent === "InteractionResolved"
      ? { interactionKind: "external-block" }
      : {}),
    ...(pierEvent === "InteractionResolved"
      ? {
          interactionOutcome:
            nativeState === "error" ? "failed" : "completed",
        }
      : {}),
    ...(promptSnippet ? { promptSnippet } : {}),
  }) + "\\n";
  try {
    pierAppend(log, line);
  } catch {
    // Pier status reporting must never affect the amp run.
  }
}

export default function (amp) {
  // 不做加载合成 SessionStart：amp 自身的 session.start 是真实会话开始
  // 信号（下方订阅）；合成版在插件工厂按会话/子代理多次执行的宿主上会
  // 打穿主状态（omp task subagent 教训）。图标点亮由 launch 先验层承担。
  const blockedThreads = new Set();
  const threadGenerations = new Map();
  const threadSubscriptions = new Map();
  let disposed = false;
  let nextGeneration = 0;

  function applyThreadState(thread, state) {
    const values = [{ thread: { id: thread.id } }];
    if (state === "awaiting-approval") {
      if (blockedThreads.has(thread.id)) return;
      blockedThreads.add(thread.id);
      emitPierEvent("thread.state.awaiting-approval", ...values);
      return;
    }
    if (blockedThreads.delete(thread.id)) {
      emitPierEvent("thread.state." + state + (state === "idle" ? "" : ".resolved"), ...values);
    }
    if (state === "running" || state === "error") {
      emitPierEvent("thread.state." + state, ...values);
    }
  }

  function isCurrentObservation(threadId, generation) {
    return (
      !disposed &&
      threadGenerations.get(threadId) === generation
    );
  }

  function observeThread(thread) {
    if (
      disposed ||
      !thread ||
      typeof thread.id !== "string" ||
      !thread.state
    ) return;
    if (threadSubscriptions.has(thread.id)) return;
    const generation = ++nextGeneration;
    threadGenerations.set(thread.id, generation);
    let seenUpdate = false;
    let subscription;
    try {
      subscription = thread.state.subscribe((state) => {
        if (!isCurrentObservation(thread.id, generation)) return;
        seenUpdate = true;
        applyThreadState(thread, state);
      });
    } catch {
      if (threadGenerations.get(thread.id) === generation) {
        threadGenerations.delete(thread.id);
      }
      return;
    }
    threadSubscriptions.set(thread.id, subscription);
    if (typeof thread.state.get === "function") {
      let snapshot;
      try {
        snapshot = thread.state.get();
      } catch {
        return;
      }
      Promise.resolve(snapshot).then(
        (state) => {
          if (
            isCurrentObservation(thread.id, generation) &&
            !seenUpdate
          ) {
            applyThreadState(thread, state);
          }
        },
        () => {
          // ThreadState 水合是尽力而为；订阅仍保持有效。
        }
      );
    }
  }

  amp.on("session.start", (event, ctx) => {
    emitPierEvent("session.start", event, ctx);
    observeThread(ctx.thread);
  });

  amp.on("agent.start", (event, ctx) => {
    emitPierEvent("agent.start", event, ctx);
    observeThread(ctx.thread);
  });

  amp.on("agent.end", (event, ctx) => {
    emitPierEvent("agent.end." + event.status, event, ctx);
    observeThread(ctx.thread);
  });

  amp.onDispose(() => {
    disposed = true;
    threadGenerations.clear();
    for (const subscription of threadSubscriptions.values()) {
      try {
        subscription.unsubscribe();
      } catch {
        // 一个订阅清理失败时仍继续释放其他订阅。
      }
    }
    threadSubscriptions.clear();
    blockedThreads.clear();
  });
}
`;
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * install：非托管跳过；磁盘更高世代跳过；字节相同不落盘。
 */
export async function installAmpHooks(
  pluginPath: string = ampPluginPath()
): Promise<void> {
  await writeManagedPluginFile({
    path: pluginPath,
    source: buildAmpPluginSource(),
    label: AGENT_ID,
  });
}

/**
 * uninstall：先查 marker 再删——非托管文件绝不删除；文件不存在视为
 * 已卸载, 零副作用。
 */
export async function uninstallAmpHooks(
  pluginPath: string = ampPluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isPierManagedPluginContent(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

export function ampDetect(): boolean {
  return (
    existsSync(join(homedir(), ".config", "amp")) || commandExistsOnPath("amp")
  );
}

export const ampIntegration: AgentHookIntegration = {
  detect: ampDetect,
  id: AGENT_ID,
  runtime: {
    emittedMappings: AMP_EVENT_MAP,
    stopAuthority: "none",
  },
  install: () => installAmpHooks(),
  uninstall: () => uninstallAmpHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const AMP_PLUGIN_MARKER_TEXT = AMP_PLUGIN_MARKER;
export const AMP_PLUGIN_FILE_NAME = AMP_PLUGIN_FILE;
