import { existsSync } from "node:fs";
import { mkdir, readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import { atomicWriteFile, commandExistsOnPath } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";

const AGENT_ID: AgentKind = "amp";

/** Pier 部署到 amp 自身插件目录下的托管文件（orca AMP_PLUGIN_FILE 同名同位）。 */
const AMP_PLUGIN_FILE = "pier-agent-status.ts";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const AMP_PLUGIN_MARKER = "pier-agent-status:v1 (managed by Pier)";

/**
 * amp.on 原生事件 → pier 规范事件名（orca hook-service.ts 事件表对齐）。
 * amp 只有会话/回合/工具五个事件, 无 subagent/permission 细分。
 */
const AMP_EVENT_MAP: ReadonlyArray<{
  nativeEvent: string;
  pierEvent: string;
}> = [
  { nativeEvent: "session.start", pierEvent: "SessionStart" },
  { nativeEvent: "agent.start", pierEvent: "PromptSubmit" },
  { nativeEvent: "tool.call", pierEvent: "ToolStart" },
  { nativeEvent: "tool.result", pierEvent: "ToolComplete" },
  { nativeEvent: "agent.end", pierEvent: "Stop" },
];

export function ampPluginPath(): string {
  return join(homedir(), ".config", "amp", "plugins", AMP_PLUGIN_FILE);
}

/**
 * 插件源码是纯字符串模板（不依赖 pierHookCommand/curl——插件跑在 amp 自己
 * 的 Node 进程内, JS 直接 fetch POST, 见 AGENTS.md wave2 spec）。
 * env 五要素（PORT/TOKEN/PANEL_ID/WINDOW_ID）任一缺失即静默 no-op；
 * fire-and-forget + 1.5s 超时 + 吞异常, 绝不影响 amp 本体运行。
 */
export function buildAmpPluginSource(): string {
  const eventMapLines = AMP_EVENT_MAP.map(
    (e) => `  "${e.nativeEvent}": "${e.pierEvent}",`
  ).join("\n");
  return `// ${AMP_PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.
import type { PluginAPI } from "@ampcode/plugin";

const PIER_EVENT_MAP: Record<string, string> = {
${eventMapLines}
};

async function emitPierEvent(nativeEvent: string): Promise<void> {
  const pierEvent = PIER_EVENT_MAP[nativeEvent];
  if (!pierEvent) return;
  const port = process.env.PIER_AGENT_HOOK_PORT;
  const token = process.env.PIER_AGENT_HOOK_TOKEN;
  const panelId = process.env.PIER_PANEL_ID;
  const windowId = process.env.PIER_WINDOW_ID;
  if (!port || !token || !panelId || !windowId) return;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 1500);
  try {
    await fetch(\`http://127.0.0.1:\${port}/agent-event\`, {
      method: "POST",
      signal: controller.signal,
      headers: {
        "Content-Type": "application/json",
        Authorization: \`Bearer \${token}\`,
      },
      body: JSON.stringify({
        v: 1,
        agent: "amp",
        event: pierEvent,
        panelId,
        windowId,
      }),
    });
  } catch {
    // Pier status reporting must never affect the amp run.
  } finally {
    clearTimeout(timeout);
  }
}

export default function (amp: PluginAPI) {
  // 加载即 agent 启动：合成 SessionStart 点亮启动态图标（事件流要到首个
  // 会话/消息才有信号）。amp 自身的 session.start 事件到达时也会再 emit
  // 一次 SessionStart——双发无害, 聚合器把 SessionStart 当回合边界幂等
  // 处理。
  void emitPierEvent("session.start");

  amp.on("session.start", () => {
    void emitPierEvent("session.start");
  });

  amp.on("agent.start", () => {
    void emitPierEvent("agent.start");
  });

  amp.on("tool.call", () => {
    void emitPierEvent("tool.call");
    return { action: "allow" };
  });

  amp.on("tool.result", () => {
    void emitPierEvent("tool.result");
  });

  amp.on("agent.end", () => {
    void emitPierEvent("agent.end");
  });
}
`;
}

function isManagedAmpPlugin(content: string): boolean {
  return content.includes(AMP_PLUGIN_MARKER);
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * install：非托管同名文件绝不覆盖（orca amp 语义, console.warn 跳过）；
 * 字节相同则不落盘（幂等重装零写入）。
 */
export async function installAmpHooks(
  pluginPath: string = ampPluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing !== null && !isManagedAmpPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip install:`,
      pluginPath
    );
    return;
  }
  const source = buildAmpPluginSource();
  if (existing === source) {
    return;
  }
  await mkdir(dirname(pluginPath), { recursive: true });
  await atomicWriteFile(pluginPath, source);
}

/**
 * uninstall：先查 marker 再删——非托管文件绝不删除；文件不存在视为
 * 已卸载, 零副作用。
 */
export async function uninstallAmpHooks(
  pluginPath: string = ampPluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isManagedAmpPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

export function ampDetect(): boolean {
  return (
    existsSync(join(homedir(), ".config", "amp")) || commandExistsOnPath("amp")
  );
}

export const ampIntegration: AgentHookIntegration = {
  capability: "full",
  detect: ampDetect,
  id: AGENT_ID,
  install: () => installAmpHooks(),
  uninstall: () => uninstallAmpHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const AMP_PLUGIN_MARKER_TEXT = AMP_PLUGIN_MARKER;
export const AMP_PLUGIN_FILE_NAME = AMP_PLUGIN_FILE;
