import { existsSync } from "node:fs";
import { mkdir, readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import { atomicWriteFile, commandExistsOnPath } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";

const AGENT_ID: AgentKind = "amp";

/** Pier 部署到 amp 自身插件目录下的托管文件（同名同位）。 */
const AMP_PLUGIN_FILE = "pier-agent-status.ts";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const AMP_PLUGIN_MARKER = "pier-agent-status:v1 (managed by Pier)";

/**
 * amp.on 原生事件 → pier 规范事件名。
 * amp 只有会话/回合/工具五个事件, 无 subagent/permission 细分。
 */
const AMP_EVENT_MAP: ReadonlyArray<{
  nativeEvent: string;
  pierEvent: string;
}> = [
  { nativeEvent: "session.start", pierEvent: "SessionStart" },
  { nativeEvent: "agent.start", pierEvent: "PromptSubmit" },
  { nativeEvent: "tool.call", pierEvent: "ToolStart" },
  { nativeEvent: "tool.result", pierEvent: "ToolComplete" },
  { nativeEvent: "agent.end", pierEvent: "Stop" },
];

export function ampPluginPath(): string {
  return join(homedir(), ".config", "amp", "plugins", AMP_PLUGIN_FILE);
}

/**
 * 插件源码是纯字符串模板（不依赖 pierHookCommand/emit 脚本——插件跑在
 * amp 自己的 Node 进程内, 直接写 JSONL）。emit 用
 * `process.getBuiltinModule("node:fs")` 同步 append（同 omp 先例：
 * 同步既保文件序——聚合器按 JSONL 文件序消费, 也保证宿主退出前
 * agent.end 落盘）；旧 Node 宿主退化为异步 best-effort。
 * env 三要素（PIER_AGENT_EVENT_LOG / PIER_PANEL_ID / PIER_WINDOW_ID）任一缺失即
 * 静默 no-op；本地 append 是最佳 effort, 吞异常绝不影响 amp 本体运行。
 */
export function buildAmpPluginSource(): string {
  const eventMapLines = AMP_EVENT_MAP.map(
    (e) => `  "${e.nativeEvent}": "${e.pierEvent}",`
  ).join("\n");
  return `// ${AMP_PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.
// No top-level import declarations: process.getBuiltinModule is a runtime
// call — not an ImportDeclaration; older Node falls back to async best-effort.
// (Exception to ts-no-dynamic-import: generated file for a foreign host.)

const PIER_EVENT_MAP = {
${eventMapLines}
};

function pierAppend(log, line) {
	if (typeof process.getBuiltinModule === "function") {
		// 同步写:保文件序 + 进程退出前落盘(Bun 与 Node >= 20.16)。
		const { appendFileSync } = process.getBuiltinModule("node:fs");
		appendFileSync(log, line);
		return;
	}
	// 旧 Node 宿主退化为异步 best-effort(与旧行为一致, 不更糟)。
	import("node:fs/promises")
		.then(({ appendFile }) => appendFile(log, line))
		.catch(() => {});
}

function emitPierEvent(nativeEvent) {
  const pierEvent = PIER_EVENT_MAP[nativeEvent];
  if (!pierEvent) return;
  const log = process.env.PIER_AGENT_EVENT_LOG;
  const panelId = process.env.PIER_PANEL_ID;
  const windowId = process.env.PIER_WINDOW_ID;
  if (!log || !panelId || !windowId) return;
  const line = JSON.stringify({
    v: 1,
    kind: "agentEvent",
    ts: Date.now() * 1_000_000,
    panelId,
    windowId,
    pid: process.pid,
    agent: "amp",
    event: pierEvent,
  }) + "\\n";
  try {
    pierAppend(log, line);
  } catch {
    // Pier status reporting must never affect the amp run.
  }
}

export default function (amp) {
  // 不做加载合成 SessionStart：amp 自身的 session.start 是真实会话开始
  // 信号（下方订阅）；合成版在插件工厂按会话/子代理多次执行的宿主上会
  // 打穿主状态（omp task subagent 教训）。图标点亮由 launch 先验层承担。
  amp.on("session.start", () => {
    emitPierEvent("session.start");
  });

  amp.on("agent.start", () => {
    emitPierEvent("agent.start");
  });

  amp.on("tool.call", () => {
    emitPierEvent("tool.call");
    return { action: "allow" };
  });

  amp.on("tool.result", () => {
    emitPierEvent("tool.result");
  });

  amp.on("agent.end", () => {
    emitPierEvent("agent.end");
  });
}
`;
}

function isManagedAmpPlugin(content: string): boolean {
  return content.includes(AMP_PLUGIN_MARKER);
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * install：非托管同名文件绝不覆盖（console.warn 跳过）；
 * 字节相同则不落盘（幂等重装零写入）。
 */
export async function installAmpHooks(
  pluginPath: string = ampPluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing !== null && !isManagedAmpPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip install:`,
      pluginPath
    );
    return;
  }
  const source = buildAmpPluginSource();
  if (existing === source) {
    return;
  }
  await mkdir(dirname(pluginPath), { recursive: true });
  await atomicWriteFile(pluginPath, source);
}

/**
 * uninstall：先查 marker 再删——非托管文件绝不删除；文件不存在视为
 * 已卸载, 零副作用。
 */
export async function uninstallAmpHooks(
  pluginPath: string = ampPluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isManagedAmpPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

export function ampDetect(): boolean {
  return (
    existsSync(join(homedir(), ".config", "amp")) || commandExistsOnPath("amp")
  );
}

export const ampIntegration: AgentHookIntegration = {
  capability: "full",
  detect: ampDetect,
  id: AGENT_ID,
  install: () => installAmpHooks(),
  uninstall: () => uninstallAmpHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const AMP_PLUGIN_MARKER_TEXT = AMP_PLUGIN_MARKER;
export const AMP_PLUGIN_FILE_NAME = AMP_PLUGIN_FILE;
