import { existsSync } from "node:fs";
import { readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import { EXTRACT_STDIN_META_SCRIPT_NAME } from "../hooks-install.ts";
import { stdinIdentityExtractionLines } from "./hooks/stdin-commands.ts";
import {
  isPierManagedPluginContent,
  pierManagedPluginMarker,
  writeManagedPluginFile,
} from "./managed-plugin-file.ts";
import {
  commandExistsOnPath,
  createNestedJsonIntegration,
  isPierHookCommand,
  type NestedJsonIntegrationSpec,
  PIER_AGENT_HOOKS_DIR_MARK,
  pierHookCommandV3,
  preflightPierNestedHooksInstall,
  transformJsonConfig,
  withPierNestedHooks,
} from "./shared.ts";

/**
 * Auggie（Augment CLI）hook 事件 → pier 事件名。
 * 依据官方文档 docs.augmentcode.com/cli/hooks：
 * - 配置路径 `~/.augment/settings.json`（用户级；workspace 级
 *   `.augment/settings.json` / `settings.local.json` 优先级更高但 Pier
 *   只管用户级全局文件，与其余集成一致）。
 * - schema 与 Claude Code 同构，但 `command` 只接受带受支持扩展名的脚本
 *   路径，不能内联 shell。因此配置引用 Pier 受管 `.sh`，严格 v3 分流在
 *   脚本内部完成。
 * - 工具事件没有稳定调用编号，因此按匿名工具闭环。Stop 的 agent_stop_cause
 *   区分 end_turn、interrupted、max_iterations、empty_completion 和 error
 *   （empty_completion 是 0.36.0 binary 实测的第五值，官方文档未列；落
 *   `*` 分支 → advisory Stop，安全退化）。
 * - **PromptSubmit（2026-08-29 审计新增）**：auggie 0.36.0 已发货
 *   `PromptSubmit` hook 事件（binary 三处证据：事件名单 Whn、配置 schema
 *   enum、载荷构造 `{hook_event_name:"PromptSubmit",conversation_id,
 *   workspace_roots,user_prompt}`），官方文档尚未收录。事件名是
 *   `PromptSubmit`（非 Claude 家族的 UserPromptSubmit）。安装它获得
 *   explicit-prompt 回合重置；旧版 auggie 无此事件 → 不触发，零增量退化。
 * - stop≠idle 消歧（2026-08-25 业界对齐审计）：trusted 终态
 *   （TurnInterrupted/error）封账后，**旧版**（无 PromptSubmit 事件的
 *   auggie）同会话内没有重开通道——中断/max_iterations 后用户继续追问的
 *   整轮工具事件会被 sealed-turn 拒绝，面板冻结在 ready。因此
 *   interrupted/max_iterations 仍一律降级为 advisory `Stop`
 *   （completionObserved，后续工作可取消候选回到忙态）；error 保持
 *   trusted（错误可见性优先，残留冻结风险见对齐文档 P1-B5）。待
 *   PromptSubmit 上游文档化、可假设普遍可用后，再重审把 interrupted
 *   升级为 TurnInterrupted。
 * - timeout 单位是毫秒（非 droid/claude 家族的秒）, 默认 60000ms；这里显式
 *   写 5000（5 秒, 与其余集成的默认 5 秒告警窗口对齐, 避免用官方默认的
 *   60 秒拖慢状态反馈）。
 */
const augConfigPath = () => join(homedir(), ".augment", "settings.json");
const augHomeDir = () => join(homedir(), ".augment");
const augManagedHookPath = () =>
  join(augHomeDir(), "hooks", "pier-agent-status.sh");

function augEmit(
  agentId: AgentKind,
  nativeEvent: string,
  event:
    | "SessionStart"
    | "PromptSubmit"
    | "ToolStart"
    | "ToolComplete"
    | "Stop"
    | "error"
    | "SessionEnd"
): string {
  return pierHookCommandV3({
    agentId,
    agentInstanceId: "$_pier_agent_id",
    agentType: "$_pier_agent_type",
    event,
    metadataBase64: "$_pier_metadata_b64",
    nativeEvent,
    nativeState: "$_pier_native_state",
    parentSessionId: "$_pier_parent_session_id",
    sessionId: "$_pier_session_id",
    toolName: "$_pier_tool_name",
    toolUseId: "$_pier_tool_use_id",
    transcriptPath: "$_pier_transcript_path",
    turnId: "$_pier_turn_id",
  });
}

function extractAugStopCause(): string {
  const extractMeta = `\${${PIER_AGENT_HOOKS_DIR_MARK}}/${EXTRACT_STDIN_META_SCRIPT_NAME}`;
  return [
    `_pier_extracted_fields=$(printf '%s' "$_pier_payload" | { if [ -x "${extractMeta}" ]; then "${extractMeta}" --shell-fields "" "agent_stop_cause" "" "" "" "" "" "" ""; fi; } 2>/dev/null || true)`,
    'eval "$_pier_extracted_fields" 2>/dev/null || true',
  ].join("; ");
}

export function buildAugManagedHookScript(): string {
  const marker = pierManagedPluginMarker();
  return `#!/bin/sh
# ${marker}
# Do not edit; this file is regenerated by Pier and any changes may be lost.
${stdinIdentityExtractionLines({
  nativeStateFields: ["hook_event_name"],
}).join("\n")}
case "$_pier_native_state" in
  SessionStart)
    _pier_native_state=
    ${augEmit("aug", "SessionStart", "SessionStart")}
    ;;
  PromptSubmit)
    _pier_native_state=
    ${augEmit("aug", "PromptSubmit", "PromptSubmit")}
    ;;
  PreToolUse)
    _pier_native_state=
    ${augEmit("aug", "PreToolUse", "ToolStart")}
    ;;
  PostToolUse)
    _pier_native_state=
    ${augEmit("aug", "PostToolUse", "ToolComplete")}
    ;;
  Stop)
    ${extractAugStopCause()}
    case "$_pier_native_state" in
      error)
        ${augEmit("aug", "Stop", "error")}
        ;;
      *)
        ${augEmit("aug", "Stop", "Stop")}
        ;;
    esac
    ;;
  SessionEnd)
    _pier_native_state=
    ${augEmit("aug", "SessionEnd", "SessionEnd")}
    ;;
esac
`;
}

const AUG_SPEC: NestedJsonIntegrationSpec = {
  agentId: "aug",
  runtime: { stopAuthority: "advisory" },
  configPath: augConfigPath,
  detect: () =>
    existsSync(augHomeDir()) ||
    commandExistsOnPath("auggie") ||
    commandExistsOnPath("aug"),
  events: [
    {
      buildCommand: augManagedHookPath,
      nativeEvent: "SessionStart",
      pierEvent: "SessionStart",
    },
    {
      buildCommand: augManagedHookPath,
      nativeEvent: "PromptSubmit",
      pierEvent: "PromptSubmit",
    },
    {
      buildCommand: augManagedHookPath,
      matcher: ".*",
      nativeEvent: "PreToolUse",
      pierEvent: "ToolStart",
    },
    {
      buildCommand: augManagedHookPath,
      matcher: ".*",
      nativeEvent: "PostToolUse",
      pierEvent: "ToolComplete",
    },
    {
      buildCommand: augManagedHookPath,
      emittedPierEvents: ["Stop", "error"],
      nativeEvent: "Stop",
      pierEvent: "Stop",
    },
    {
      buildCommand: augManagedHookPath,
      nativeEvent: "SessionEnd",
      pierEvent: "SessionEnd",
    },
  ],
  // 官方 timeout 单位毫秒（非 droid/claude 家族的秒）——覆盖工厂默认的
  // "5"（会被工厂当秒写入, 在 aug 语境下变成 5ms 立即超时）。
  timeoutSeconds: 5000,
};

interface AugNestedEntry {
  hooks?: Array<{ command?: unknown }>;
}

function withoutPierAugHooks(
  settings: Record<string, unknown>,
  removeManagedPath = false
): Record<string, unknown> {
  const hooksValue = settings.hooks;
  if (!(hooksValue && typeof hooksValue === "object")) {
    return settings;
  }
  const hooks = { ...(hooksValue as Record<string, unknown>) };
  const managedPath = augManagedHookPath();
  let changed = false;
  for (const [event, value] of Object.entries(hooks)) {
    if (!Array.isArray(value)) {
      continue;
    }
    const kept: unknown[] = [];
    let eventChanged = false;
    for (const entry of value) {
      if (!(entry && typeof entry === "object")) {
        kept.push(entry);
        continue;
      }
      const nested = (entry as AugNestedEntry).hooks;
      if (!Array.isArray(nested)) {
        kept.push(entry);
        continue;
      }
      const keptNested = nested.filter(
        (hook) =>
          !(
            (removeManagedPath && hook?.command === managedPath) ||
            isPierHookCommand(hook?.command)
          )
      );
      if (keptNested.length === nested.length) {
        kept.push(entry);
        continue;
      }
      changed = true;
      eventChanged = true;
      if (keptNested.length > 0) {
        kept.push({ ...entry, hooks: keptNested });
      }
    }
    if (!eventChanged) {
      continue;
    }
    if (kept.length === 0) {
      delete hooks[event];
    } else {
      hooks[event] = kept;
    }
  }
  return changed ? { ...settings, hooks } : settings;
}

async function isManagedAugScript(): Promise<boolean> {
  try {
    return isPierManagedPluginContent(
      await readFile(augManagedHookPath(), "utf8")
    );
  } catch {
    return false;
  }
}

async function removeManagedAugScript(): Promise<void> {
  try {
    const content = await readFile(augManagedHookPath(), "utf8");
    if (isPierManagedPluginContent(content)) {
      await rm(augManagedHookPath(), { force: true });
    }
  } catch {
    // Missing/unreadable files are already effectively uninstalled.
  }
}

const augBase = createNestedJsonIntegration(AUG_SPEC);

export async function installAugHooks(
  platform: NodeJS.Platform = process.platform
): Promise<void> {
  // 官方只为 macOS/Linux 提供 `.sh` hook；Pier 的严格 v3 emit runtime 也
  // 是 POSIX 实现。Windows 虽接受 `.ps1`/`.cmd`，但在有等价 runtime 与
  // 实机测试前明确不安装，避免写入看似有效但无法上报的配置。
  if (platform !== "darwin" && platform !== "linux") {
    console.warn(
      `[agent-hooks:aug] unsupported hook platform, skip: ${platform}`
    );
    return;
  }
  const result = await writeManagedPluginFile({
    label: "aug",
    mode: 0o755,
    path: augManagedHookPath(),
    source: buildAugManagedHookScript(),
  });
  if (result === "skipped-unmanaged" || result === "skipped-newer") {
    return;
  }
  await transformJsonConfig(
    augConfigPath(),
    (settings) => {
      if (!preflightPierNestedHooksInstall(settings, AUG_SPEC)) {
        return settings;
      }
      return withPierNestedHooks(withoutPierAugHooks(settings, true), AUG_SPEC);
    },
    "aug"
  );
}

export async function uninstallAugHooks(): Promise<void> {
  const removeManagedPath = await isManagedAugScript();
  await transformJsonConfig(
    augConfigPath(),
    (settings) => withoutPierAugHooks(settings, removeManagedPath),
    "aug"
  );
  await removeManagedAugScript();
}

export const augIntegration: typeof augBase = {
  ...augBase,
  install: () => installAugHooks(),
  uninstall: uninstallAugHooks,
};
