import { existsSync } from "node:fs";
import { chmod, mkdir, readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import {
  atomicWriteFile,
  pierHookCommandWithStdinSessionId,
} from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";

const AGENT_ID: AgentKind = "cline";

/**
 * Cline hooks — 依据官方文档：
 * - docs.cline.bot/cli/cli-reference：另有 CLI `--hooks-dir` 机制
 *   （默认 `~/.cline/hooks`，可用 `CLINE_HOOKS_DIR` 环境变量覆盖），但该
 *   页未列出支持的事件名全集, 且是 per-invocation flag（非全局始终生效）。
 *   本集成 v1 不使用该机制, 与下方文件制目录并存不冲突（用户仍可自行用
 *   --hooks-dir 接入其他自动化）。
 * - cline.bot/blog/cline-v3-36-hooks：全局机制是**文件制**——
 *   `~/Documents/Cline/Rules/Hooks/<EventName>`（无扩展名、可执行文件,
 *   通过 stdin 接收 JSON payload, 文件名必须与事件名完全一致）。也存在
 *   项目级 `.clinerules/hooks/`，但 pier 只装全局目录（跨项目生效,
 *   与其余集成的「一次安装全局生效」纪律一致）。
 *   六个受支持事件：TaskStart / TaskResume / UserPromptSubmit /
 *   PreToolUse / PostToolUse / TaskCancel。
 *
 * 事件映射：TaskStart→SessionStart, TaskResume→SessionStart,
 * UserPromptSubmit→PromptSubmit, PreToolUse→ToolStart,
 * PostToolUse→ToolComplete, TaskCancel→Stop。
 * capability "full"。
 *
 * 每个事件对应一个独立 shell 脚本文件：`#!/bin/sh` + 先读掉 stdin
 * （避免子进程不消费 stdin 导致上游阻塞/SIGPIPE, 与 kiro 集成同样的
 * 保险处理）+ 静态嵌入事件名的 pier curl 命令；文件头写托管 marker 注释
 * （install 幂等比对 + uninstall 删除前必查）。chmod 0o755 使其可执行。
 * 已存在的非托管同名文件绝不覆盖——只 warn 并跳过该文件（其余文件仍照常
 * 安装/卸载，互不影响）。uninstall 只删含 marker 的文件。
 */

const CLINE_MARKER = "pier-agent-status:v1 (managed by Pier)";

const CLINE_EVENTS: ReadonlyArray<{
  fileName: string;
  pierEvent: string;
}> = [
  { fileName: "TaskStart", pierEvent: "SessionStart" },
  { fileName: "TaskResume", pierEvent: "SessionStart" },
  { fileName: "UserPromptSubmit", pierEvent: "PromptSubmit" },
  { fileName: "PreToolUse", pierEvent: "ToolStart" },
  { fileName: "PostToolUse", pierEvent: "ToolComplete" },
  { fileName: "TaskCancel", pierEvent: "Stop" },
  // 正常完成必须有回合边界信号——缺了它状态会卡在 tool/processing 直到
  // 30min TTL 衰减（loomdesk cline eventStatusMap 同款映射）。
  { fileName: "TaskComplete", pierEvent: "Stop" },
  { fileName: "PreCompact", pierEvent: "processing" },
];

export function clineHooksDir(): string {
  return join(homedir(), "Documents", "Cline", "Rules", "Hooks");
}

/** 生成单个事件的 hook 脚本源码（#!/bin/sh + payload sessionId 抽取 + pier 命令）。 */
export function buildClineHookScript(pierEvent: string): string {
  return `#!/bin/sh
# ${CLINE_MARKER}
# Do not edit; this file is regenerated by Pier and any changes may be lost.
${pierHookCommandWithStdinSessionId(AGENT_ID, pierEvent)}
`;
}

function isManagedScript(content: string): boolean {
  return content.includes(CLINE_MARKER);
}

async function readScriptFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * 部署单个事件脚本：非托管同名文件绝不覆盖（warn 跳过）；字节相同不落盘
 * （幂等重装零写入）；写入后 chmod 0o755。
 */
async function deployEventScript(
  dir: string,
  fileName: string,
  pierEvent: string
): Promise<void> {
  const path = join(dir, fileName);
  const source = buildClineHookScript(pierEvent);
  const existing = await readScriptFile(path);
  if (existing !== null && !isManagedScript(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged hook file present, skip install:`,
      path
    );
    return;
  }
  if (existing !== source) {
    await mkdir(dir, { recursive: true });
    await atomicWriteFile(path, source);
  }
  await chmod(path, 0o755);
}

/**
 * 卸载单个事件脚本：仅当文件存在且含托管 marker 时删除；非托管文件 warn
 * 跳过；文件不存在视为已卸载。
 */
async function removeEventScript(dir: string, fileName: string): Promise<void> {
  const path = join(dir, fileName);
  const existing = await readScriptFile(path);
  if (existing === null) {
    return;
  }
  if (!isManagedScript(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged hook file present, skip uninstall:`,
      path
    );
    return;
  }
  await rm(path, { force: true });
}

export async function installClineHooks(
  dir: string = clineHooksDir()
): Promise<void> {
  for (const event of CLINE_EVENTS) {
    await deployEventScript(dir, event.fileName, event.pierEvent);
  }
}

export async function uninstallClineHooks(
  dir: string = clineHooksDir()
): Promise<void> {
  for (const event of CLINE_EVENTS) {
    await removeEventScript(dir, event.fileName);
  }
}

function clineDetect(): boolean {
  return (
    existsSync(join(homedir(), "Documents", "Cline")) ||
    existsSync(join(homedir(), ".cline"))
  );
}

export const clineIntegration: AgentHookIntegration = {
  capability: "full",
  detect: clineDetect,
  id: AGENT_ID,
  install: () => installClineHooks(),
  uninstall: () => uninstallClineHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const CLINE_HOOK_MARKER = CLINE_MARKER;
export const CLINE_EVENT_FILE_NAMES = CLINE_EVENTS.map((e) => e.fileName);
