import { existsSync } from "node:fs";
import { readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import {
  isPierManagedPluginContent,
  pierManagedPluginMarker,
  writeManagedPluginFile,
} from "./managed-plugin-file.ts";
import { commandExistsOnPath, pierHookCommandV3WithStdin } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";

const AGENT_ID: AgentKind = "cline";

/**
 * Cline hooks — 依据官方文档：
 * - CLI `--hooks-dir` 默认 `~/.cline/hooks`；当前 SDK 搜索路径同时包含
 *   `~/Documents/Cline/Hooks`、`~/.cline/hooks` 与项目级目录。Pier 选择
 *   CLI 默认目录，避免依赖 Documents 路径且保持一次安装全局生效。
 * - macOS/Linux 的平台文件名是无扩展名可执行文件；Windows 官方文件名是
 *   `<EventName>.ps1`。Pier 严格 v3 runtime 当前仅有已执行验证的 POSIX
 *   实现，因此 Windows 明确不安装，不能仅换扩展名伪装成已支持。
 *   当前 SDK 的文件配置支持 TaskStart / TaskResume / TaskCancel /
 *   TaskComplete / TaskError / PreToolUse / PostToolUse / UserPromptSubmit /
 *   SessionShutdown。`PreCompact` 虽存在于事件类型，却未接入文件配置映射，
 *   因此不能安装一个上游不会调用的文件。
 *
 * 事件映射：TaskStart→SessionStart, TaskResume→running（恢复是新的活跃回合）,
 * UserPromptSubmit→PromptSubmit, PreToolUse→ToolStart,
 * PostToolUse→ToolComplete, TaskComplete→TurnCompleted,
 * TaskCancel→TurnInterrupted, TaskError→error,
 * SessionShutdown→SessionEnd。
 * 状态证据由事件矩阵统一声明。
 *
 * 每个事件对应一个独立 shell 脚本文件：`#!/bin/sh` + 先读掉 stdin
 * （避免子进程不消费 stdin 导致上游阻塞/SIGPIPE, 与 kiro 集成同样的
 * 保险处理）+ 静态嵌入事件名的严格 v3 emit 命令；文件头写托管 marker 注释
 * （install 幂等比对 + uninstall 删除前必查）。chmod 0o755 使其可执行。
 * 已存在的非托管同名文件绝不覆盖——只 warn 并跳过该文件（其余文件仍照常
 * 安装/卸载，互不影响）。uninstall 只删含 marker 的文件。
 */

const CLINE_MARKER = pierManagedPluginMarker();

const CLINE_EVENTS: ReadonlyArray<{
  fileName: string;
  pierEvent: string;
}> = [
  { fileName: "TaskStart", pierEvent: "SessionStart" },
  { fileName: "TaskResume", pierEvent: "running" },
  { fileName: "UserPromptSubmit", pierEvent: "PromptSubmit" },
  { fileName: "PreToolUse", pierEvent: "ToolStart" },
  { fileName: "PostToolUse", pierEvent: "ToolComplete" },
  { fileName: "TaskComplete", pierEvent: "TurnCompleted" },
  { fileName: "TaskCancel", pierEvent: "TurnInterrupted" },
  { fileName: "TaskError", pierEvent: "error" },
  { fileName: "SessionShutdown", pierEvent: "SessionEnd" },
];

/** 旧版本曾写入、但当前不再支持安装的事件；只参与迁移与卸载清理。 */
const CLINE_LEGACY_EVENT_FILE_NAMES = ["PreCompact"] as const;

export function clineHooksDir(): string {
  return join(homedir(), ".cline", "hooks");
}

export function clineHookFileName(
  nativeEvent: string,
  platform: NodeJS.Platform = process.platform
): string {
  return platform === "win32" ? `${nativeEvent}.ps1` : nativeEvent;
}

/** 生成单个事件的 hook 脚本源码（#!/bin/sh + payload sessionId 抽取 + pier 命令）。 */
export function buildClineHookScript(
  pierEvent: string,
  nativeEvent: string = pierEvent,
  platform: NodeJS.Platform = process.platform
): string {
  if (platform === "win32") {
    throw new Error("Cline hooks are unsupported on Windows");
  }
  const isToolEvent =
    nativeEvent === "PreToolUse" || nativeEvent === "PostToolUse";
  return `#!/bin/sh
# ${CLINE_MARKER}
# Do not edit; this file is regenerated by Pier and any changes may be lost.
${pierHookCommandV3WithStdin({
  agentId: AGENT_ID,
  event: pierEvent,
  nativeEvent,
  ...(isToolEvent
    ? {
        toolNamePaths: ["tool_call.name"],
        toolUseIdPaths: ["tool_call.id"],
      }
    : {}),
} as Parameters<typeof pierHookCommandV3WithStdin>[0])}
`;
}

async function readScriptFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * 部署单个事件脚本：非托管/更高世代跳过；字节相同不落盘；写入后 chmod 0o755。
 */
async function deployEventScript(
  dir: string,
  fileName: string,
  pierEvent: string,
  platform: NodeJS.Platform
): Promise<void> {
  const path = join(dir, clineHookFileName(fileName, platform));
  const source = buildClineHookScript(pierEvent, fileName, platform);
  await writeManagedPluginFile({
    path,
    source,
    label: AGENT_ID,
    ...(platform === "win32" ? {} : { mode: 0o755 }),
  });
}

/**
 * 卸载单个事件脚本：仅当文件存在且含托管 marker 时删除；非托管文件 warn
 * 跳过；文件不存在视为已卸载。
 */
async function removeEventScript(
  dir: string,
  fileName: string,
  platform: NodeJS.Platform
): Promise<void> {
  const path = join(dir, clineHookFileName(fileName, platform));
  await removeManagedClineScript(path);
}

async function removeManagedClineScript(path: string): Promise<void> {
  const existing = await readScriptFile(path);
  if (existing === null) {
    return;
  }
  if (!isPierManagedPluginContent(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged hook file present, skip uninstall:`,
      path
    );
    return;
  }
  await rm(path, { force: true });
}

async function cleanupLegacyClineHooks(): Promise<void> {
  const legacyDir = join(homedir(), "Documents", "Cline", "Rules", "Hooks");
  const fileNames = [
    ...CLINE_EVENTS.map((event) => event.fileName),
    ...CLINE_LEGACY_EVENT_FILE_NAMES,
  ];
  for (const fileName of fileNames) {
    await removeManagedClineScript(join(legacyDir, fileName));
    await removeManagedClineScript(join(legacyDir, `${fileName}.ps1`));
  }
}

export async function installClineHooks(
  dir: string = clineHooksDir(),
  platform: NodeJS.Platform = process.platform
): Promise<void> {
  if (platform === "win32") {
    console.warn("[agent-hooks:cline] unsupported hook platform, skip: win32");
    return;
  }
  for (const event of CLINE_EVENTS) {
    await deployEventScript(dir, event.fileName, event.pierEvent, platform);
  }
}

export async function uninstallClineHooks(
  dir: string = clineHooksDir(),
  platform: NodeJS.Platform = process.platform
): Promise<void> {
  for (const event of CLINE_EVENTS) {
    await removeEventScript(dir, event.fileName, platform);
  }
}

function clineDetect(): boolean {
  return (
    existsSync(join(homedir(), "Documents", "Cline")) ||
    existsSync(join(homedir(), ".cline")) ||
    commandExistsOnPath("cline")
  );
}

export const clineIntegration: AgentHookIntegration = {
  detect: clineDetect,
  id: AGENT_ID,
  runtime: {
    emittedMappings: CLINE_EVENTS.map(({ fileName, pierEvent }) => ({
      nativeEvent: fileName,
      pierEvent,
    })),
    stopAuthority: "none",
  },
  install: async () => {
    await cleanupLegacyClineHooks();
    await installClineHooks();
  },
  uninstall: async () => {
    await cleanupLegacyClineHooks();
    await uninstallClineHooks();
  },
};

/** marker 常量导出（测试断言用）。 */
export const CLINE_HOOK_MARKER = CLINE_MARKER;
export const CLINE_HOOK_EVENTS = CLINE_EVENTS;
export const CLINE_EVENT_FILE_NAMES = CLINE_HOOK_EVENTS.map((e) => e.fileName);
