import { existsSync } from "node:fs";
import { mkdir, readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import { atomicWriteFile, commandExistsOnPath } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";

const AGENT_ID: AgentKind = "kilo";

/** Pier 部署的独立插件文件（不放 kilo 自身安装目录下, opencode 同款布局）。 */
const PLUGIN_FILE = "pier-agent-status.ts";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const PLUGIN_MARKER = "pier-agent-status:v1 (managed by Pier)";

/**
 * Kilo Code CLI 插件 — 依据官方文档 kilo.ai/docs/automate/extending/plugins：
 * - 插件目录**自动加载**、无需 config 注册：`~/.config/kilo/plugin/` 下每个
 *   `.ts`/`.js` 文件在启动时自动注册（也存在 `.kilo/plugin/` 与旧版
 *   `.kilocode/plugin/` 项目级目录, 但 pier 只装全局目录, 与其余「一次
 *   安装全局生效」的集成纪律一致）。
 * - 官方最小插件示例的导出形状是 `export default { id, server }`，
 *   其中 `server` 是 `Plugin` 类型的工厂函数
 *   `async (ctx) => ({ ...hook 实现... })`——不是 prompt 猜测的
 *   `export default { event: async ({event}) => {...} }` 直接形状（那是
 *   server 工厂*返回值*里的一个 hook 键, 不是顶层导出）。本文件按官方
 *   真实形状生成源码。
 * - 事件总线映射（Events 参考页确认的事件名, SOURCE 证据）：
 *   session.created→SessionStart, session.idle→Stop, session.error→error,
 *   session.deleted→SessionEnd, session.status(busy/retry)→running、
 *   (idle)→Stop（kilo 是 opencode fork, EventSessionStatus 事件同源;
 *   Events 参考页 Session 分类明确列出 session.status——模型 busy/retry
 *   心跳是每回合必发的 TURN_RESET, 防 Stop 后工具事件被永久吸收;
 *   见聚合器不变式「映射 Stop 必须同时映射 TURN_RESET」）。
 *   permission 事件官方名 `permission.asked`/`permission.replied`
 *   （Events 参考页 Permission 分类明确列出; opencode SDK 里叫
 *   permission.updated, kilo fork 重命名了此事件, SOURCE）。
 *   用户消息提交事件：Events 页列有 `command.executed`, 但 payload
 *   形状未确认是否含 prompt.submit 动作——拿不准的宁缺毋滥,
 *   不装 PromptSubmit; session.status(busy) 已提供 TURN_RESET,
 *   PromptSubmit 缺失不影响正确性。
 *   tool：tool.execute.before→ToolStart, tool.execute.after→ToolComplete
 *   （与 opencode 集成同名事件, SOURCE 确认一致）。
 * - emit 用 appendFileSync（pierAppend 模板; Bun 宿主
 *   process.getBuiltinModule 可用, 旧 Node 退化异步 best-effort）。
 *   无顶层 import 声明（electron-vite 模板字面量扫描陷阱）。
 *   三 PIER_ 环境变量任一缺失即静默 no-op, 吞异常。
 * capability "full"。
 */
export function kiloPluginPath(): string {
  return join(homedir(), ".config", "kilo", "plugin", PLUGIN_FILE);
}

export function buildKiloPluginSource(pluginId: AgentKind = AGENT_ID): string {
  return `// ${PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.
// Deliberately no top-level import declarations: electron-vite scans
// template literals in main's bundle and can otherwise inject an invalid
// CommonJS shim into the ESM output. process.getBuiltinModule is a runtime
// call — not an ImportDeclaration — so the scan stays inert; available in
// Bun (kilo's host) and Node >= 20.16.

function pierAppend(log, line) {
	if (typeof process.getBuiltinModule === "function") {
		// 同步写:保文件序 + 进程退出前落盘(Bun 与 Node >= 20.16)。
		const { appendFileSync } = process.getBuiltinModule("node:fs");
		appendFileSync(log, line);
		return;
	}
	// ts-no-dynamic-import 例外：运行时 import() 非 ImportDeclaration,
	// 旧 Node 宿主退化为异步 best-effort(与旧行为一致, 不更糟)。
	import("node:fs/promises")
		.then(({ appendFile }) => appendFile(log, line))
		.catch(() => {});
}

function pierEmit(pierEvent) {
	const log = process.env.PIER_AGENT_EVENT_LOG;
	const panelId = process.env.PIER_PANEL_ID;
	const windowId = process.env.PIER_WINDOW_ID;
	if (!log || !panelId || !windowId) return;
	const line = JSON.stringify({
		v: 1,
		kind: "agentEvent",
		ts: Date.now() * 1_000_000,
		panelId,
		windowId,
		pid: process.pid,
		agent: "${pluginId}",
		event: pierEvent,
	}) + "\\n";
	try {
		pierAppend(log, line);
	} catch {
		// best-effort, never throw into the agent's own event loop
	}
}

function mapPierEvent(event) {
	if (!event || typeof event.type !== "string") return null;
	if (event.type === "session.created") return "SessionStart";
	if (event.type === "session.idle") return "Stop";
	if (event.type === "session.error") return "error";
	if (event.type === "session.deleted") return "SessionEnd";
	if (event.type === "session.status") {
		// SDK EventSessionStatus: properties.status.type = busy/retry/idle
		// (kilo 是 opencode fork, SDK 事件同源; kilo.ai/docs/automate/extending/plugins
		// Events 参考页 Session 分类确认 session.status)。
		// busy/retry 是模型推进心跳——TURN_RESET, 防 Stop 后工具事件被吸收
		// (聚合器不变式:映射 Stop 的集成必须同时映射 TURN_RESET 事件)。
		const statusType =
			event.properties && event.properties.status && event.properties.status.type;
		if (statusType === "busy" || statusType === "retry") return "running";
		if (statusType === "idle") return "Stop";
		return null;
	}
	if (event.type === "permission.asked") return "PermissionRequest";
	if (event.type === "permission.replied") return "processing";
	return null;
}

const server = async () => {
	// session.created 提供真实 SessionStart 信号, 不再合成。
	return {
		event: async ({ event }) => {
			const mapped = mapPierEvent(event);
			if (mapped) pierEmit(mapped);
		},
		"tool.execute.before": async () => {
			pierEmit("ToolStart");
		},
		"tool.execute.after": async () => {
			pierEmit("ToolComplete");
		},
	};
};

export default { id: "${pluginId}-agent-status", server };
`;
}

function isManagedPlugin(content: string): boolean {
  return content.includes(PLUGIN_MARKER);
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

export async function installKiloHooks(
  pluginPath: string = kiloPluginPath()
): Promise<void> {
  const source = buildKiloPluginSource();
  const existing = await readPluginFile(pluginPath);
  if (existing !== null && !isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip install:`,
      pluginPath
    );
    return;
  }
  if (existing !== source) {
    await mkdir(dirname(pluginPath), { recursive: true });
    await atomicWriteFile(pluginPath, source);
  }
}

/**
 * uninstall：检查 marker 再删, 非托管文件绝不删除, 文件不存在视为已卸载。
 */
export async function uninstallKiloHooks(
  pluginPath: string = kiloPluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

function kiloDetect(): boolean {
  return (
    existsSync(join(homedir(), ".config", "kilo")) ||
    existsSync(join(homedir(), ".kilocode")) ||
    commandExistsOnPath("kilo")
  );
}

export const kiloIntegration: AgentHookIntegration = {
  capability: "full",
  detect: kiloDetect,
  id: AGENT_ID,
  install: () => installKiloHooks(),
  uninstall: () => uninstallKiloHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const KILO_PLUGIN_MARKER_TEXT = PLUGIN_MARKER;
export const KILO_PLUGIN_FILE_NAME = PLUGIN_FILE;
