import { existsSync } from "node:fs";
import { mkdir, readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import { atomicWriteFile, commandExistsOnPath } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";

const AGENT_ID: AgentKind = "kilo";

/** Pier 部署的独立插件文件（不放 kilo 自身安装目录下, opencode 同款布局）。 */
const PLUGIN_FILE = "pier-agent-status.ts";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const PLUGIN_MARKER = "pier-agent-status:v1 (managed by Pier)";

/**
 * Kilo Code CLI 插件 — 依据官方文档 kilo.ai/docs/automate/extending/plugins：
 * - 插件目录**自动加载**、无需 config 注册：`~/.config/kilo/plugin/` 下每个
 *   `.ts`/`.js` 文件在启动时自动注册（也存在 `.kilo/plugin/` 与旧版
 *   `.kilocode/plugin/` 项目级目录, 但 pier 只装全局目录, 与其余「一次
 *   安装全局生效」的集成纪律一致）。
 * - 官方最小插件示例的导出形状是 `export default { id, server }`，
 *   其中 `server` 是 `Plugin` 类型的工厂函数
 *   `async (ctx) => ({ ...hook 实现... })`——不是 prompt 猜测的
 *   `export default { event: async ({event}) => {...} }` 直接形状（那是
 *   server 工厂*返回值*里的一个 hook 键, 不是顶层导出）。本文件按官方
 *   真实形状生成源码。
 * - 事件总线映射（官方 Events 参考页确认的事件名）：
 *   session.created→SessionStart, session.idle→Stop, session.error→error,
 *   session.deleted→SessionEnd。permission 事件官方名是
 *   `permission.asked`/`permission.replied`（prompt 猜测的
 *   "permission.updated" 不存在, 按官方实际名改用 permission.asked→
 *   PermissionRequest）。用户消息提交事件：官方 Events 列表仅确认
 *   `message.updated` 存在于 Message 分类下, 未明确其 payload 是否含
 *   role 字段可用于区分「用户提交」与「模型输出」——拿不准的宁缺毋滥,
 *   本集成不装 PromptSubmit（注释说明, 与「宁缺毋滥」纪律一致）。
 *   tool 类：tool.execute.before→ToolStart, tool.execute.after→
 *   ToolComplete（与 opencode 集成同名事件, 语义确认一致）。
 * - emit 用插件上下文提供的全局 fetch（Node/Bun 运行时内置）, 读
 *   process.env.PIER_*，缺失 no-op，1.5s AbortController 超时，吞异常
 *   （与 opencode.ts 插件体手法一致）。
 * capability "full"。
 */
export function kiloPluginPath(): string {
  return join(homedir(), ".config", "kilo", "plugin", PLUGIN_FILE);
}

export function buildKiloPluginSource(pluginId: AgentKind = AGENT_ID): string {
  return `// ${PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.

async function emitPierEvent(pierEvent) {
  const port = process.env.PIER_AGENT_HOOK_PORT;
  const token = process.env.PIER_AGENT_HOOK_TOKEN;
  const panelId = process.env.PIER_PANEL_ID;
  const windowId = process.env.PIER_WINDOW_ID;
  if (!port || !token || !panelId || !windowId) return;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 1500);
  try {
    await fetch(\`http://127.0.0.1:\${port}/agent-event\`, {
      method: "POST",
      signal: controller.signal,
      headers: {
        "Content-Type": "application/json",
        Authorization: \`Bearer \${token}\`,
      },
      body: JSON.stringify({
        v: 1,
        agent: "${pluginId}",
        event: pierEvent,
        panelId,
        windowId,
      }),
    });
  } catch {
    // Pier status reporting must never affect the agent run.
  } finally {
    clearTimeout(timeout);
  }
}

function mapPierEvent(event) {
  if (!event || typeof event.type !== "string") return null;
  if (event.type === "session.created") return "SessionStart";
  if (event.type === "session.idle") return "Stop";
  if (event.type === "session.error") return "error";
  if (event.type === "session.deleted") return "SessionEnd";
  if (event.type === "permission.asked") return "PermissionRequest";
  if (event.type === "permission.replied") return "processing";
  return null;
}

const server = async () => {
  // 加载即 agent 启动：合成 SessionStart 点亮启动态图标（事件流要到首个
  // 会话/消息才有信号）。
  await emitPierEvent("SessionStart");
  return {
    event: async ({ event }) => {
      const mapped = mapPierEvent(event);
      if (mapped) await emitPierEvent(mapped);
    },
    "tool.execute.before": async () => {
      await emitPierEvent("ToolStart");
    },
    "tool.execute.after": async () => {
      await emitPierEvent("ToolComplete");
    },
  };
};

export default { id: "${pluginId}-agent-status", server };
`;
}

function isManagedPlugin(content: string): boolean {
  return content.includes(PLUGIN_MARKER);
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

export async function installKiloHooks(
  pluginPath: string = kiloPluginPath()
): Promise<void> {
  const source = buildKiloPluginSource();
  const existing = await readPluginFile(pluginPath);
  if (existing !== null && !isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip install:`,
      pluginPath
    );
    return;
  }
  if (existing !== source) {
    await mkdir(dirname(pluginPath), { recursive: true });
    await atomicWriteFile(pluginPath, source);
  }
}

/**
 * uninstall：检查 marker 再删, 非托管文件绝不删除, 文件不存在视为已卸载。
 */
export async function uninstallKiloHooks(
  pluginPath: string = kiloPluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

function kiloDetect(): boolean {
  return (
    existsSync(join(homedir(), ".config", "kilo")) ||
    existsSync(join(homedir(), ".kilocode")) ||
    commandExistsOnPath("kilo")
  );
}

export const kiloIntegration: AgentHookIntegration = {
  capability: "full",
  detect: kiloDetect,
  id: AGENT_ID,
  install: () => installKiloHooks(),
  uninstall: () => uninstallKiloHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const KILO_PLUGIN_MARKER_TEXT = PLUGIN_MARKER;
export const KILO_PLUGIN_FILE_NAME = PLUGIN_FILE;
