import { existsSync } from "node:fs";
import { mkdir, readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import { atomicWriteFile, commandExistsOnPath } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";

const AGENT_ID: AgentKind = "mimo-code";

/**
 * mimo-code 是 opencode 的 fork（orca mimo/hook-service.ts 复用
 * opencode 插件源码, 仅换 hook 路径后缀）——插件目录同为
 * `<config>/plugins/`, 目录下任何文件均自动加载。这是对 opencode.json
 * 的 `plugin` 数组注册机制的**补充**而非替代：两条加载路径并存, 目录扫描
 * 让免注册的插件也能生效, 并不意味着 config plugin 数组本身失效或被
 * 绕过, 二者可同时使用。pier 集成选择目录投放路径, 是因为它是更简单的
 * 一条（无需额外写 config 数组条目, 幂等判定也更简单）。
 */
const PLUGIN_FILE = "mimo-code-agent-status.js";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const PLUGIN_MARKER = "pier-agent-status:v1 (managed by Pier)";

/** mimo-code 配置目录：$MIMOCODE_HOME/config 优先, 否则 XDG ~/.config/mimocode。 */
function mimoCodeConfigDir(): string {
  const home = process.env.MIMOCODE_HOME;
  if (home && home.length > 0) {
    return join(home, "config");
  }
  return join(homedir(), ".config", "mimocode");
}

export function mimoCodePluginPath(): string {
  return join(mimoCodeConfigDir(), "plugins", PLUGIN_FILE);
}

/**
 * 插件源码：与 opencode 同一套事件表/emit 逻辑（mimo-code 是 opencode
 * 家族 fork, 仅 agent id 不同）。JS 直接 fetch POST, env 五要素任一缺失
 * 即静默 no-op, fire-and-forget + 1.5s 超时 + 吞异常。
 *
 * permission 事件按 XiaomiMiMo/MiMo-Code main 分支 SDK 生成类型
 * (packages/sdk/js/src/gen/types.gen.ts) 使用 permission.updated /
 * permission.replied——与 opencode SDK 完全一致。**注意**：mimo 家族内
 * app 层还有 permission.asked 名字, 但 plugin API 收到的事件走 SDK 类型,
 * 名字是 permission.updated。
 */
export function buildMimoCodePluginSource(): string {
  return `// ${PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.
import { appendFile } from "node:fs/promises";

async function emitPierEvent(pierEvent) {
  const log = process.env.PIER_AGENT_EVENT_LOG;
  const panelId = process.env.PIER_PANEL_ID;
  const windowId = process.env.PIER_WINDOW_ID;
  if (!log || !panelId || !windowId) return;
  const line = JSON.stringify({
    v: 1,
    kind: "agentEvent",
    ts: Date.now() * 1_000_000,
    panelId,
    windowId,
    pid: process.pid,
    agent: "mimo-code",
    event: pierEvent,
  }) + "\\n";
  try {
    await appendFile(log, line);
  } catch {
    // Pier status reporting must never affect the agent run.
  }
}

function mapPierEvent(event) {
  if (!event || typeof event.type !== "string") return null;
  if (event.type === "session.created") return "SessionStart";
  if (event.type === "session.idle") return "Stop";
  if (event.type === "session.error") return "error";
  if (event.type === "session.status") {
    // 同 opencode（MiMo 是 opencode fork, SDK 事件同源）:
    // busy/retry 推进心跳, idle 回合结束。
    const statusType =
      event.properties && event.properties.status && event.properties.status.type;
    if (statusType === "busy" || statusType === "retry") return "running";
    if (statusType === "idle") return "Stop";
    return null;
  }
  if (event.type === "tui.command.execute") {
    const command = event.properties && event.properties.command;
    return command === "prompt.submit" ? "PromptSubmit" : null;
  }
  if (event.type === "permission.updated") return "PermissionRequest";
  if (event.type === "permission.replied") return "processing";
  return null;
}

export const PierAgentStatus = async () => {
  // 加载即 agent 启动：合成 SessionStart 点亮启动态图标（事件流要到首个
  // 会话/消息才有信号）。
  await emitPierEvent("SessionStart");
  return {
    event: async ({ event }) => {
      const mapped = mapPierEvent(event);
      if (mapped) await emitPierEvent(mapped);
    },
    "tool.execute.before": async () => {
      await emitPierEvent("ToolStart");
    },
    "tool.execute.after": async () => {
      await emitPierEvent("ToolComplete");
    },
  };
};
`;
}

function isManagedPlugin(content: string): boolean {
  return content.includes(PLUGIN_MARKER);
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * install：无 config 注册步骤——plugins/ 目录下任意文件自动加载（opencode
 * 家族机制）。非托管同名文件绝不覆盖；字节相同不落盘（幂等零写入）。
 */
export async function installMimoCodeHooks(
  pluginPath: string = mimoCodePluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing !== null && !isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip install:`,
      pluginPath
    );
    return;
  }
  const source = buildMimoCodePluginSource();
  if (existing === source) {
    return;
  }
  await mkdir(dirname(pluginPath), { recursive: true });
  await atomicWriteFile(pluginPath, source);
}

/**
 * uninstall：先查 marker 再删——非托管文件绝不删除；文件不存在视为
 * 已卸载, 零副作用。
 */
export async function uninstallMimoCodeHooks(
  pluginPath: string = mimoCodePluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

/**
 * detect：mimo-code 配置目录存在或 mimo 命令在 PATH 上（orca
 * resolveSourceConfigDir 的探测逻辑对齐——XDG 目录或已有 home 均视为已装）。
 */
function mimoCodeDetect(): boolean {
  return existsSync(mimoCodeConfigDir()) || commandExistsOnPath("mimo-code");
}

export const mimoCodeIntegration: AgentHookIntegration = {
  capability: "full",
  detect: mimoCodeDetect,
  id: AGENT_ID,
  install: () => installMimoCodeHooks(),
  uninstall: () => uninstallMimoCodeHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const MIMO_CODE_PLUGIN_MARKER_TEXT = PLUGIN_MARKER;
export const MIMO_CODE_PLUGIN_FILE_NAME = PLUGIN_FILE;
