import { existsSync } from "node:fs";
import { readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { isAbsolute, join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import {
  isPierManagedPluginContent,
  pierManagedPluginMarker,
  writeManagedPluginFile,
} from "./managed-plugin-file.ts";
import { JAVASCRIPT_PROMPT_SNIPPET_SOURCE } from "./prompt-snippet-source.ts";
import { commandExistsOnPath } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";
import { JAVASCRIPT_LOCKED_APPEND_SOURCE } from "./writer-lock-source.ts";

const AGENT_ID: AgentKind = "mimo-code";
const MIMO_CODE_EMITTED_MAPPINGS = [
  { nativeEvent: "session.created", pierEvent: "SessionStart" },
  { nativeEvent: "session.deleted", pierEvent: "SessionEnd" },
  { nativeEvent: "chat.message", pierEvent: "PromptSubmit" },
  { nativeEvent: "session.pre", pierEvent: "running" },
  { nativeEvent: "session.post=completed", pierEvent: "TurnCompleted" },
  { nativeEvent: "session.post=cancelled", pierEvent: "TurnInterrupted" },
  { nativeEvent: "session.post=error", pierEvent: "error" },
  { nativeEvent: "permission.asked", pierEvent: "InteractionRequested" },
  { nativeEvent: "permission.replied", pierEvent: "InteractionResolved" },
  { nativeEvent: "question.asked", pierEvent: "InteractionRequested" },
  { nativeEvent: "question.replied", pierEvent: "InteractionResolved" },
  { nativeEvent: "question.rejected", pierEvent: "InteractionResolved" },
  { nativeEvent: "tool.execute.before", pierEvent: "ToolStart" },
  { nativeEvent: "tool.execute.after", pierEvent: "ToolComplete" },
  { nativeEvent: "message.part.updated=completed", pierEvent: "ToolComplete" },
  { nativeEvent: "message.part.updated=error", pierEvent: "ToolComplete" },
] as const;

/**
 * mimo-code 是 opencode 的 fork（复用
 * opencode 插件源码, 仅换 hook 路径后缀）——插件目录同为
 * `<config>/plugins/`, 目录下任何文件均自动加载。这是对 opencode.json
 * 的 `plugin` 数组注册机制的**补充**而非替代：两条加载路径并存, 目录扫描
 * 让免注册的插件也能生效, 并不意味着 config plugin 数组本身失效或被
 * 绕过, 二者可同时使用。pier 集成选择目录投放路径, 是因为它是更简单的
 * 一条（无需额外写 config 数组条目, 幂等判定也更简单）。
 */
const PLUGIN_FILE = "mimo-code-agent-status.js";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const PLUGIN_MARKER = pierManagedPluginMarker();

/** mimo-code 配置目录：绝对 $MIMOCODE_HOME/config 优先，其次 XDG 配置根。 */
export function mimoCodeConfigDir(): string {
  const home = process.env.MIMOCODE_HOME;
  if (home && home.length > 0) {
    if (!isAbsolute(home)) {
      throw new Error("MIMOCODE_HOME must be an absolute path");
    }
    return join(home, "config");
  }
  const xdgConfigHome = process.env.XDG_CONFIG_HOME;
  if (xdgConfigHome && isAbsolute(xdgConfigHome)) {
    return join(xdgConfigHome, "mimocode");
  }
  return join(homedir(), ".config", "mimocode");
}

export function mimoCodePluginPath(): string {
  return join(mimoCodeConfigDir(), "plugins", PLUGIN_FILE);
}

/**
 * 插件源码：固定支持 MiMo Code v0.1.9（发布提交 c045a989，当前同版本
 * main 提交 f91eb633）的插件格式：
 * default `{id, server}`；同时保留命名 factory 供该版本的兼容加载器使用。
 * emit 用
 * `process.getBuiltinModule("node:fs")` 同步 append（同 omp 先例：
 * 同步既保文件序——聚合器按 JSONL 文件序消费, 也保证宿主退出前
 * session.idle 落盘）；旧 Node 宿主退化为异步 best-effort。
 * env 三要素任一缺失即静默 no-op, fire-and-forget + 吞异常。
 *
 * permission 事件以固定提交
 * `c045a9891069000b112079bb10bdc8828d75eb6e` 的内部总线为准：
 * Permission.ask 发布 permission.asked（Request.id），Permission.reply 发布
 * permission.replied（requestID / reply），plugin/index.ts 的 subscribeAll
 * 将总线事件原样投给 hosted plugin。SDK 生成类型中的 permission.updated /
 * permissionID / response 与该运行时链路存在漂移，不能作为插件载荷依据。
 */
export function buildMimoCodePluginSource(): string {
  return `// ${PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.
// No top-level import declarations: process.getBuiltinModule is a runtime
// call — not an ImportDeclaration; older Node falls back to async best-effort.
// (Exception to ts-no-dynamic-import: generated file for a foreign host.)

${JAVASCRIPT_LOCKED_APPEND_SOURCE}
${JAVASCRIPT_PROMPT_SNIPPET_SOURCE}

function pierSessionIdFrom(event) {
  const values = Array.isArray(event) ? [...event] : [event];
  values.push(...values.map((value) => value && value.properties));
  for (const value of values) {
    if (!value || typeof value !== "object") continue;
    for (const key of ["sessionId", "sessionID", "session_id"]) {
      if (typeof value[key] === "string" && value[key]) return value[key];
    }
    const session = value.info || value.session || value.thread;
    if (session && typeof session === "object") {
      for (const key of ["id", "sessionId", "sessionID", "session_id"]) {
        if (typeof session[key] === "string" && session[key]) return session[key];
      }
    }
  }
  return undefined;
}

function pierToolIdFrom(event) {
  const values = Array.isArray(event) ? event : [event];
  for (const value of values) {
    if (!value || typeof value !== "object") continue;
    for (const key of ["callID", "callId", "toolCallID", "toolCallId", "toolUseId", "tool_use_id"]) {
      if (typeof value[key] === "string" && value[key]) return value[key];
    }
  }
  return undefined;
}

const pierParentSessionIds = new Map();

function emitPierEvent(pierEvent, nativeEvent, rawEvent, extra = {}) {
  const log = process.env.PIER_AGENT_EVENT_LOG;
  const panelId = process.env.PIER_PANEL_ID;
  const windowId = process.env.PIER_WINDOW_ID;
  if (!log || !panelId || !windowId) return;
  const sessionId = pierSessionIdFrom(rawEvent);
  const toolUseId = pierToolIdFrom(rawEvent);
  const properties = rawEvent && !Array.isArray(rawEvent) && rawEvent.properties;
  const info = properties && (properties.info || properties.session);
  const nativeState =
    properties && properties.status && typeof properties.status.type === "string"
      ? properties.status.type
      : undefined;
  const discoveredParentSessionId =
    (info && (info.parentID || info.parentId || info.parent_id)) ||
    (properties && (properties.parentID || properties.parentId || properties.parent_id));
  if (
    sessionId &&
    typeof discoveredParentSessionId === "string" &&
    discoveredParentSessionId
  ) {
    pierParentSessionIds.set(sessionId, discoveredParentSessionId);
  }
  const parentSessionId = sessionId
    ? pierParentSessionIds.get(sessionId)
    : undefined;
  const isSubagent = parentSessionId !== undefined;
  const promptSnippet =
    pierEvent === "PromptSubmit" ? pierPromptSnippetFrom(rawEvent) : undefined;
  const line = JSON.stringify({
    v: 3,
    kind: "agentEvent",
    ts: Date.now() * 1_000_000,
    panelId,
    windowId,
    pid: process.pid,
    agent: "mimo-code",
    event: pierEvent,
    nativeEvent,
    ...pierSpawnGenerationFromEnv(),
    ...(nativeState ? { nativeState } : {}),
    ...(isSubagent ? { actorHint: "subagent" } : {}),
    ...(typeof parentSessionId === "string" && parentSessionId
      ? { parentSessionId }
      : {}),
    ...(sessionId ? { sessionId } : {}),
    ...(toolUseId ? { toolUseId } : {}),
    ...(promptSnippet ? { promptSnippet } : {}),
    ...extra,
  }) + "\\n";
  try {
    pierAppend(log, line);
  } catch {
    // Pier status reporting must never affect the agent run.
  }
  if (nativeEvent === "session.deleted" && sessionId) {
    pierParentSessionIds.delete(sessionId);
  }
}

function pierInteraction(event, kind, outcome) {
  const p = event.properties || {};
  emitPierEvent(
    outcome ? "InteractionResolved" : "InteractionRequested",
    event.type,
    event,
    {
      interactionId: p.id || p.requestID,
      interactionKind: kind,
      ...(outcome ? { interactionOutcome: outcome } : {}),
    }
  );
}

function pierPermissionOutcome(reply) {
  if (reply === "once" || reply === "always")
    return "accepted";
  if (reply === "reject") return "rejected";
  return "unknown";
}

export const PierAgentStatus = () => {
  // 不做加载合成 SessionStart：session.created→SessionStart 是真实信号；
  // 合成版在工厂按会话/子代理多次执行的宿主上会打穿主状态（omp 教训）。
  return {
    event: ({ event }) => {
      if (!event || typeof event.type !== "string") return;
      const p = event.properties || {};
      if (event.type === "session.created") {
        if (!(p.info && p.info.parentID))
          emitPierEvent("SessionStart", event.type, event);
      } else if (event.type === "session.deleted") {
        if (!(p.info && p.info.parentID))
          emitPierEvent("SessionEnd", event.type, event);
      } else if (event.type === "permission.asked")
        pierInteraction(event, "permission");
      else if (event.type === "permission.replied")
        pierInteraction(event, "permission", pierPermissionOutcome(p.reply));
      else if (event.type === "question.asked")
        pierInteraction(event, "question");
      else if (event.type === "question.replied")
        pierInteraction(event, "question", "completed");
      else if (event.type === "question.rejected")
        pierInteraction(event, "question", "rejected");
      else if (event.type === "message.part.updated") {
        const part = p.part;
        const state = part && part.type === "tool" && part.state && part.state.status;
        if (state === "completed" || state === "error")
          emitPierEvent("ToolComplete", "message.part.updated=" + state, event, {
            toolUseId: part.callID,
            toolName: part.tool,
            nativeState: state,
          });
      }
    },
    "chat.message": (input, output) => {
      emitPierEvent("PromptSubmit", "chat.message", input, {
        turnId: input.messageID || (output.message && output.message.id),
        promptSnippet: pierPromptSnippetFrom({ content: output.parts }, output.message),
      });
    },
    "session.pre": (input) => {
      if (input.agentID === "main")
        emitPierEvent("running", "session.pre", input);
    },
    "session.post": (input) => {
      if (input.agentID !== "main") return;
      if (input.outcome === "completed")
        emitPierEvent("TurnCompleted", "session.post=completed", input, { nativeState: "completed" });
      else if (input.outcome === "cancelled")
        emitPierEvent("TurnInterrupted", "session.post=cancelled", input, { nativeState: "cancelled" });
      else if (input.outcome === "error")
        emitPierEvent("error", "session.post=error", input, { nativeState: "error" });
    },
    "tool.execute.before": (input) => {
      emitPierEvent("ToolStart", "tool.execute.before", input, { toolUseId: input.callID, toolName: input.tool });
    },
    "tool.execute.after": (input) => {
      emitPierEvent("ToolComplete", "tool.execute.after", input, { toolUseId: input.callID, toolName: input.tool });
    },
  };
};

export default { id: "pier-agent-status", server: PierAgentStatus };
`;
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * install：无 config 注册步骤——plugins/ 目录下任意文件自动加载。
 * 非托管/更高世代跳过；字节相同不落盘。
 */
export async function installMimoCodeHooks(
  pluginPath: string = mimoCodePluginPath()
): Promise<void> {
  await writeManagedPluginFile({
    path: pluginPath,
    source: buildMimoCodePluginSource(),
    label: AGENT_ID,
  });
}

/**
 * uninstall：先查 marker 再删——非托管文件绝不删除；文件不存在视为
 * 已卸载, 零副作用。
 */
export async function uninstallMimoCodeHooks(
  pluginPath: string = mimoCodePluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isPierManagedPluginContent(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

/**
 * detect：mimo-code 配置目录存在或 mimo 命令在 PATH 上
 * （XDG 目录或已有 home 均视为已装）。
 */
function mimoCodeDetect(): boolean {
  return existsSync(mimoCodeConfigDir()) || commandExistsOnPath("mimo");
}

export const mimoCodeIntegration: AgentHookIntegration = {
  detect: mimoCodeDetect,
  id: AGENT_ID,
  runtime: {
    emittedMappings: MIMO_CODE_EMITTED_MAPPINGS,
    stopAuthority: "authoritative",
  },
  install: () => installMimoCodeHooks(),
  uninstall: () => uninstallMimoCodeHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const MIMO_CODE_PLUGIN_MARKER_TEXT = PLUGIN_MARKER;
export const MIMO_CODE_PLUGIN_FILE_NAME = PLUGIN_FILE;
