import { existsSync } from "node:fs";
import { mkdir, readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import { JAVASCRIPT_PROMPT_SNIPPET_SOURCE } from "./prompt-snippet-source.ts";
import { atomicWriteFile, commandExistsOnPath } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";
import { JAVASCRIPT_LOCKED_APPEND_SOURCE } from "./writer-lock-source.ts";

const AGENT_ID: AgentKind = "mimo-code";

/**
 * mimo-code 是 opencode 的 fork（复用
 * opencode 插件源码, 仅换 hook 路径后缀）——插件目录同为
 * `<config>/plugins/`, 目录下任何文件均自动加载。这是对 opencode.json
 * 的 `plugin` 数组注册机制的**补充**而非替代：两条加载路径并存, 目录扫描
 * 让免注册的插件也能生效, 并不意味着 config plugin 数组本身失效或被
 * 绕过, 二者可同时使用。pier 集成选择目录投放路径, 是因为它是更简单的
 * 一条（无需额外写 config 数组条目, 幂等判定也更简单）。
 */
const PLUGIN_FILE = "mimo-code-agent-status.js";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const PLUGIN_MARKER = "pier-agent-status:v1 (managed by Pier)";

/** mimo-code 配置目录：$MIMOCODE_HOME/config 优先, 否则 XDG ~/.config/mimocode。 */
function mimoCodeConfigDir(): string {
  const home = process.env.MIMOCODE_HOME;
  if (home && home.length > 0) {
    return join(home, "config");
  }
  return join(homedir(), ".config", "mimocode");
}

export function mimoCodePluginPath(): string {
  return join(mimoCodeConfigDir(), "plugins", PLUGIN_FILE);
}

/**
 * 插件源码：与 opencode 同一套事件表/emit 逻辑（mimo-code 是 opencode
 * 家族 fork, 仅 agent id 不同）。emit 用
 * `process.getBuiltinModule("node:fs")` 同步 append（同 omp 先例：
 * 同步既保文件序——聚合器按 JSONL 文件序消费, 也保证宿主退出前
 * session.idle 落盘）；旧 Node 宿主退化为异步 best-effort。
 * env 三要素任一缺失即静默 no-op, fire-and-forget + 吞异常。
 *
 * permission 事件按 XiaomiMiMo/MiMo-Code main 分支 SDK 生成类型
 * (packages/sdk/js/src/gen/types.gen.ts) 使用 permission.updated /
 * permission.replied——与 opencode SDK 完全一致。**注意**：mimo 家族内
 * app 层还有 permission.asked 名字, 但 plugin API 收到的事件走 SDK 类型,
 * 名字是 permission.updated。
 */
export function buildMimoCodePluginSource(): string {
  return `// ${PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.
// No top-level import declarations: process.getBuiltinModule is a runtime
// call — not an ImportDeclaration; older Node falls back to async best-effort.
// (Exception to ts-no-dynamic-import: generated file for a foreign host.)

${JAVASCRIPT_LOCKED_APPEND_SOURCE}
${JAVASCRIPT_PROMPT_SNIPPET_SOURCE}

function pierSessionIdFrom(event) {
  const values = Array.isArray(event) ? [...event] : [event];
  values.push(...values.map((value) => value && value.properties));
  for (const value of values) {
    if (!value || typeof value !== "object") continue;
    for (const key of ["sessionId", "sessionID", "session_id"]) {
      if (typeof value[key] === "string" && value[key]) return value[key];
    }
    const session = value.info || value.session || value.thread;
    if (session && typeof session === "object") {
      for (const key of ["id", "sessionId", "sessionID", "session_id"]) {
        if (typeof session[key] === "string" && session[key]) return session[key];
      }
    }
  }
  return undefined;
}

function pierToolIdFrom(event) {
  const values = Array.isArray(event) ? event : [event];
  for (const value of values) {
    if (!value || typeof value !== "object") continue;
    for (const key of ["callID", "callId", "toolCallID", "toolCallId", "toolUseId", "tool_use_id"]) {
      if (typeof value[key] === "string" && value[key]) return value[key];
    }
  }
  return undefined;
}

const pierParentSessionIds = new Map();

function emitPierEvent(pierEvent, nativeEvent, rawEvent) {
  const log = process.env.PIER_AGENT_EVENT_LOG;
  const panelId = process.env.PIER_PANEL_ID;
  const windowId = process.env.PIER_WINDOW_ID;
  if (!log || !panelId || !windowId) return;
  const sessionId = pierSessionIdFrom(rawEvent);
  const toolUseId = pierToolIdFrom(rawEvent);
  const properties = rawEvent && !Array.isArray(rawEvent) && rawEvent.properties;
  const info = properties && (properties.info || properties.session);
  const nativeState =
    properties && properties.status && typeof properties.status.type === "string"
      ? properties.status.type
      : undefined;
  const discoveredParentSessionId =
    (info && (info.parentID || info.parentId || info.parent_id)) ||
    (properties && (properties.parentID || properties.parentId || properties.parent_id));
  if (
    sessionId &&
    typeof discoveredParentSessionId === "string" &&
    discoveredParentSessionId
  ) {
    pierParentSessionIds.set(sessionId, discoveredParentSessionId);
  }
  const parentSessionId = sessionId
    ? pierParentSessionIds.get(sessionId)
    : undefined;
  const isSubagent = parentSessionId !== undefined;
  const promptSnippet =
    pierEvent === "PromptSubmit" ? pierPromptSnippetFrom(rawEvent) : undefined;
  const line = JSON.stringify({
    v: 2,
    kind: "agentEvent",
    ts: Date.now() * 1_000_000,
    panelId,
    windowId,
    pid: process.pid,
    agent: "mimo-code",
    event: pierEvent,
    nativeEvent,
    ...(nativeState ? { nativeState } : {}),
    ...(isSubagent ? { actorHint: "subagent" } : {}),
    ...(typeof parentSessionId === "string" && parentSessionId
      ? { parentSessionId }
      : {}),
    ...(sessionId ? { sessionId } : {}),
    ...(toolUseId ? { toolUseId } : {}),
    ...(promptSnippet ? { promptSnippet } : {}),
  }) + "\\n";
  try {
    pierAppend(log, line);
  } catch {
    // Pier status reporting must never affect the agent run.
  }
  if (nativeEvent === "session.deleted" && sessionId) {
    pierParentSessionIds.delete(sessionId);
  }
}

function mapPierEvent(event) {
  if (!event || typeof event.type !== "string") return null;
  if (event.type === "session.created") return "SessionStart";
  if (event.type === "session.idle") return "Stop";
  if (event.type === "session.error") return "error";
  if (event.type === "session.deleted") return "SessionEnd";
  if (event.type === "session.status") {
    // 同 opencode（MiMo 是 opencode fork, SDK 事件同源）:
    // busy/retry 推进心跳, idle 回合结束。
    const statusType =
      event.properties && event.properties.status && event.properties.status.type;
    if (statusType === "busy" || statusType === "retry") return "running";
    if (statusType === "idle") return "Stop";
    return null;
  }
  if (event.type === "tui.command.execute") {
    const command = event.properties && event.properties.command;
    return command === "prompt.submit" ? "PromptSubmit" : null;
  }
  if (event.type === "permission.updated") return "PermissionRequest";
  if (event.type === "permission.replied") return "processing";
  return null;
}

export const PierAgentStatus = () => {
  // 不做加载合成 SessionStart：session.created→SessionStart 是真实信号；
  // 合成版在工厂按会话/子代理多次执行的宿主上会打穿主状态（omp 教训）。
  return {
    event: ({ event }) => {
      const mapped = mapPierEvent(event);
      if (mapped) emitPierEvent(mapped, event.type, event);
    },
    "tool.execute.before": (...args) => {
      emitPierEvent("ToolStart", "tool.execute.before", args);
    },
    "tool.execute.after": (...args) => {
      emitPierEvent("ToolComplete", "tool.execute.after", args);
    },
  };
};
`;
}

function isManagedPlugin(content: string): boolean {
  return content.includes(PLUGIN_MARKER);
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * install：无 config 注册步骤——plugins/ 目录下任意文件自动加载（opencode
 * 家族机制）。非托管同名文件绝不覆盖；字节相同不落盘（幂等零写入）。
 */
export async function installMimoCodeHooks(
  pluginPath: string = mimoCodePluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing !== null && !isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip install:`,
      pluginPath
    );
    return;
  }
  const source = buildMimoCodePluginSource();
  if (existing === source) {
    return;
  }
  await mkdir(dirname(pluginPath), { recursive: true });
  await atomicWriteFile(pluginPath, source);
}

/**
 * uninstall：先查 marker 再删——非托管文件绝不删除；文件不存在视为
 * 已卸载, 零副作用。
 */
export async function uninstallMimoCodeHooks(
  pluginPath: string = mimoCodePluginPath()
): Promise<void> {
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

/**
 * detect：mimo-code 配置目录存在或 mimo 命令在 PATH 上
 * （XDG 目录或已有 home 均视为已装）。
 */
function mimoCodeDetect(): boolean {
  return existsSync(mimoCodeConfigDir()) || commandExistsOnPath("mimo-code");
}

export const mimoCodeIntegration: AgentHookIntegration = {
  capability: "full",
  detect: mimoCodeDetect,
  id: AGENT_ID,
  runtime: { stopAuthority: "authoritative" },
  install: () => installMimoCodeHooks(),
  uninstall: () => uninstallMimoCodeHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const MIMO_CODE_PLUGIN_MARKER_TEXT = PLUGIN_MARKER;
export const MIMO_CODE_PLUGIN_FILE_NAME = PLUGIN_FILE;
