import { existsSync } from "node:fs";
import { mkdir, readFile, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { AgentKind } from "@shared/contracts/agent.ts";
import { atomicWriteFile, transformJsonConfig } from "./shared.ts";
import type { AgentHookIntegration } from "./types.ts";

const AGENT_ID: AgentKind = "opencode";

/**
 * 插件文件名。部署进 opencode 的**自动发现目录**（<configRoot>/plugins/）——
 * 实证发现 config `plugin` 数组的绝对路径注册在当前 opencode 版本不生效
 * （官方文档也只承诺自动发现目录）, 发现目录方案已实测启动即加载。
 */
const PLUGIN_FILE = "pier-agent-status.js";
/** 旧版本部署名与位置（config 数组注册 + ~/.pier/plugins/）——遗留清理用。 */
const LEGACY_PLUGIN_FILE = "opencode-agent-status.js";

/** 托管标记：写在插件源码内, install 幂等比对 + uninstall 删除前必查。 */
const PLUGIN_MARKER = "pier-agent-status:v1 (managed by Pier)";

/** 自动发现目录内的插件路径：跟随实际存在的 config 根目录。 */
export function opencodePluginPath(): string {
  return join(dirname(opencodeConfigPath()), "plugins", PLUGIN_FILE);
}

function legacyPluginPath(): string {
  return join(homedir(), ".pier", "plugins", LEGACY_PLUGIN_FILE);
}

/** opencode config 路径候选：两者取已存在者, 都不存在时默认第一个。 */
function candidateConfigPaths(): string[] {
  return [
    join(homedir(), ".config", "opencode", "opencode.json"),
    join(homedir(), ".opencode", "opencode.json"),
  ];
}

export function opencodeConfigPath(): string {
  for (const candidate of candidateConfigPaths()) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }
  return candidateConfigPaths()[0] as string;
}

/**
 * 插件源码：opencode plugin factory 返回事件表 + tool.execute 钩子。
 * JS 直接 fetch POST（不走 shell/curl）, env 五要素任一缺失即静默
 * no-op, fire-and-forget + 1.5s 超时 + 吞异常。
 * 事件映射（anomalyco/opencode SDK 生成类型 packages/sdk/js/src/gen/
 * types.gen.ts 为准, 以下两处此前对不上官方类型, 已修正）：
 * session.created→SessionStart, session.idle→Stop, session.error→error,
 * tui.command.execute(prompt.submit)→PromptSubmit（原以为键位名是
 * "input_submit"——那是 keybinds 配置里的动作 id, 但 tui.command.execute
 * 事件 payload 的 command 字段实际值是 "prompt.submit"，EventTuiCommandExecute
 * 类型的 command 联合里没有 "input_submit"），permission.updated→
 * PermissionRequest（SDK 类型只有 EventPermissionUpdated /
 * EventPermissionReplied 两种, 没有 "permission.asked"——旧文档页过时）,
 * permission.replied→processing, session.status(busy/retry)→running、
 * (idle)→Stop（EventSessionStatus——模型忙碌/重试中的推进心跳）,
 * tool.execute.before→ToolStart, tool.execute.after→ToolComplete。
 */
export function buildOpencodePluginSource(
  pluginId: AgentKind = AGENT_ID
): string {
  return `// ${PLUGIN_MARKER}
// Do not edit; this file is regenerated by Pier and any changes may be lost.
import { appendFile } from "node:fs/promises";

async function emitPierEvent(pierEvent) {
  const log = process.env.PIER_AGENT_EVENT_LOG;
  const panelId = process.env.PIER_PANEL_ID;
  const windowId = process.env.PIER_WINDOW_ID;
  if (!log || !panelId || !windowId) return;
  const line = JSON.stringify({
    v: 1,
    kind: "agentEvent",
    ts: Date.now() * 1_000_000,
    panelId,
    windowId,
    pid: process.pid,
    agent: "${pluginId}",
    event: pierEvent,
  }) + "\\n";
  try {
    await appendFile(log, line);
  } catch {
    // Pier status reporting must never affect the agent run.
  }
}

function mapPierEvent(event) {
  if (!event || typeof event.type !== "string") return null;
  if (event.type === "session.created") return "SessionStart";
  if (event.type === "session.idle") return "Stop";
  if (event.type === "session.error") return "error";
  if (event.type === "session.status") {
    // SDK EventSessionStatus: properties.status.type = busy/retry/idle
    // （sst/opencode packages/sdk/js/src/gen/types.gen.ts SessionStatus 联合）。
    // busy/retry 是模型推进/重试中——缺了它长回合只剩 prompt.submit 一跳。
    const statusType =
      event.properties && event.properties.status && event.properties.status.type;
    if (statusType === "busy" || statusType === "retry") return "running";
    if (statusType === "idle") return "Stop";
    return null;
  }
  if (event.type === "tui.command.execute") {
    const command = event.properties && event.properties.command;
    return command === "prompt.submit" ? "PromptSubmit" : null;
  }
  if (event.type === "permission.updated") return "PermissionRequest";
  if (event.type === "permission.replied") return "processing";
  return null;
}

export const PierAgentStatus = async () => {
  // 加载即 agent 启动：合成 SessionStart 点亮启动态图标（事件流要到首个
  // 会话/消息才有信号）。
  await emitPierEvent("SessionStart");
  return {
    event: async ({ event }) => {
      const mapped = mapPierEvent(event);
      if (mapped) await emitPierEvent(mapped);
    },
    "tool.execute.before": async () => {
      await emitPierEvent("ToolStart");
    },
    "tool.execute.after": async () => {
      await emitPierEvent("ToolComplete");
    },
  };
};
`;
}

function isManagedPlugin(content: string): boolean {
  return content.includes(PLUGIN_MARKER);
}

async function readPluginFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * 部署插件文件：非托管同名文件绝不覆盖（console.warn 跳过）；字节相同
 * 不落盘（幂等重装零写入）。返回 true 表示可以（或已经）安全部署——
 * 供 config 注册步骤判断是否继续写 plugin 数组。
 */
async function deployPluginFile(
  pluginPath: string,
  source: string
): Promise<boolean> {
  const existing = await readPluginFile(pluginPath);
  if (existing !== null && !isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip install:`,
      pluginPath
    );
    return false;
  }
  if (existing !== source) {
    await mkdir(dirname(pluginPath), { recursive: true });
    await atomicWriteFile(pluginPath, source);
  }
  return true;
}

function pluginArray(config: Record<string, unknown>): unknown[] {
  return Array.isArray(config.plugin) ? [...(config.plugin as unknown[])] : [];
}

function pluginSpec(entry: unknown): string | null {
  if (typeof entry === "string") {
    return entry;
  }
  if (Array.isArray(entry) && typeof entry[0] === "string") {
    return entry[0];
  }
  return null;
}

/**
 * 只认 Pier 自己写过的注册条目。注意不能按裸文件名匹配——loomdesk 也用
 * opencode-agent-status.js 文件名（部署在 ~/.loomdesk/plugins/）, 误删会
 * 破坏用户的 loomdesk 集成。
 */
function isPierPluginSpec(spec: string): boolean {
  return (
    spec.includes(`.pier/plugins/${LEGACY_PLUGIN_FILE}`) ||
    spec.includes("pier-agent-status")
  );
}

/**
 * 纯函数：移除 config `plugin` 数组里的 pier 注册条目（旧版本布局遗留）。
 * 无匹配时原样返回输入引用（无变化不落盘守卫依赖引用相等）。
 * plugin 数组清空时保留空数组（不凭空删除用户已有的键结构）。
 */
export function withoutPierOpencodePlugin(
  config: Record<string, unknown>
): Record<string, unknown> {
  const plugin = pluginArray(config);
  const filtered = plugin.filter((entry) => {
    const spec = pluginSpec(entry);
    return spec === null || !isPierPluginSpec(spec);
  });
  if (filtered.length === plugin.length) {
    return config;
  }
  return { ...config, plugin: filtered };
}

/** 清旧布局：config 数组注册条目 + ~/.pier/plugins 下的旧插件文件。 */
async function cleanupOpencodeLegacy(configPath: string): Promise<void> {
  if (existsSync(configPath)) {
    await transformJsonConfig(configPath, withoutPierOpencodePlugin, AGENT_ID);
  }
  const legacy = await readPluginFile(legacyPluginPath());
  if (legacy !== null && isManagedPlugin(legacy)) {
    await rm(legacyPluginPath(), { force: true });
  }
}

export async function installOpencodeHooks(
  configPath: string = opencodeConfigPath(),
  pluginPath: string = opencodePluginPath()
): Promise<void> {
  await cleanupOpencodeLegacy(configPath);
  await deployPluginFile(pluginPath, buildOpencodePluginSource());
}

/**
 * uninstall：先撤销 config 注册, 再删托管插件文件（检查 marker 再删,
 * 非托管文件绝不删除）。文件不存在视为已卸载。
 */
export async function uninstallOpencodeHooks(
  configPath: string = opencodeConfigPath(),
  pluginPath: string = opencodePluginPath()
): Promise<void> {
  await cleanupOpencodeLegacy(configPath);
  const existing = await readPluginFile(pluginPath);
  if (existing === null) {
    return;
  }
  if (!isManagedPlugin(existing)) {
    console.warn(
      `[agent-hooks:${AGENT_ID}] unmanaged plugin file present, skip uninstall:`,
      pluginPath
    );
    return;
  }
  await rm(pluginPath, { force: true });
}

function opencodeDetect(): boolean {
  return candidateConfigPaths().some((p) => existsSync(p));
}

export const opencodeIntegration: AgentHookIntegration = {
  capability: "full",
  detect: opencodeDetect,
  id: AGENT_ID,
  install: () => installOpencodeHooks(),
  uninstall: () => uninstallOpencodeHooks(),
};

/** marker 常量导出（测试断言用）。 */
export const OPENCODE_PLUGIN_MARKER_TEXT = PLUGIN_MARKER;
export const OPENCODE_PLUGIN_FILE_NAME = PLUGIN_FILE;
