/**
 * Extended PATH language matrix rows + display-only entries.
 */

import type { LanguageMatrixRow } from "./types.ts";

const GIT = [".git"] as const;

export const EXTENDED_PATH_LANGUAGE_MATRIX: readonly LanguageMatrixRow[] = [
  {
    editorLanguageId: "cpp",
    extensions: [
      ".c",
      ".h",
      ".cc",
      ".cpp",
      ".cxx",
      ".hpp",
      ".hxx",
      ".hh",
      ".m",
      ".mm",
    ],
    id: "cpp",
    lsp: {
      binaryHint: "clangd",
      command: "clangd",
      displayName: "C / C++ / Objective-C",
      id: "clangd",
      installCommand: "brew install llvm",
      languageIdByExtension: {
        ".c": "c",
        ".cc": "cpp",
        ".cpp": "cpp",
        ".cxx": "cpp",
        ".h": "c",
        ".hh": "cpp",
        ".hpp": "cpp",
        ".hxx": "cpp",
        ".m": "objective-c",
        ".mm": "objective-cpp",
      },
      languageIds: ["c", "cpp", "objective-c", "objective-cpp"],
      priority: 70,
      rootMarkers: [
        "compile_commands.json",
        "compile_flags.txt",
        "CMakeLists.txt",
        ".clangd",
      ],
    },
  },
  {
    editorLanguageId: "csharp",
    extensions: [".cs"],
    id: "csharp",
    lsp: {
      binaryHint: "csharp-ls|OmniSharp",
      command: "csharp-ls",
      commandCandidates: ["csharp-ls", "OmniSharp"],
      displayName: "C#",
      id: "csharp-ls",
      installCommand: "dotnet tool install -g csharp-ls",
      languageIds: ["csharp"],
      priority: 70,
      rootMarkers: ["global.json", "Directory.Build.props", ".git"],
    },
  },
  {
    editorLanguageId: "dart",
    extensions: [".dart"],
    id: "dart",
    lsp: {
      args: ["language-server", "--protocol=lsp"],
      binaryHint: "dart",
      command: "dart",
      displayName: "Dart",
      id: "dart",
      installCommand:
        "Install Dart SDK (https://dart.dev/get-dart) so `dart` is on PATH",
      languageIds: ["dart"],
      priority: 70,
      rootMarkers: ["pubspec.yaml", ".git"],
    },
  },
  {
    basenameMatchers: ["dockerfile", "dockerfile.*"],
    editorLanguageId: "dockerfile",
    extensions: [".dockerfile"],
    id: "dockerfile",
    lsp: {
      args: ["--stdio"],
      binaryHint: "docker-langserver",
      command: "docker-langserver",
      displayName: "Dockerfile",
      id: "docker-langserver",
      installCommand: "npm i -g dockerfile-language-server-nodejs",
      languageIds: ["dockerfile"],
      priority: 70,
      rootMarkers: [...GIT],
    },
  },
  {
    editorLanguageId: "elixir",
    extensions: [".ex", ".exs"],
    id: "elixir",
    lsp: {
      binaryHint: "elixir-ls|language_server.sh",
      command: "elixir-ls",
      displayName: "Elixir",
      id: "elixir-ls",
      installCommand:
        "Install ElixirLS and ensure language_server.sh or elixir-ls is on PATH",
      languageIds: ["elixir"],
      launchCandidates: [
        { args: [], command: "elixir-ls" },
        { args: [], command: "language_server.sh" },
      ],
      priority: 70,
      rootMarkers: ["mix.exs", ".git"],
    },
  },
  {
    editorLanguageId: "java",
    extensions: [".java"],
    id: "java",
    lsp: {
      binaryHint: "jdtls",
      command: "jdtls",
      displayName: "Java",
      id: "jdtls",
      installCommand: "brew install jdtls",
      languageIds: ["java"],
      priority: 70,
      rootMarkers: [
        "pom.xml",
        "build.gradle",
        "build.gradle.kts",
        "settings.gradle",
        "settings.gradle.kts",
      ],
    },
  },
  {
    editorLanguageId: "kotlin",
    extensions: [".kt", ".kts"],
    id: "kotlin",
    lsp: {
      binaryHint: "kotlin-language-server",
      command: "kotlin-language-server",
      displayName: "Kotlin",
      id: "kotlin-language-server",
      installCommand: "brew install kotlin-language-server",
      languageIds: ["kotlin"],
      priority: 70,
      rootMarkers: [
        "settings.gradle",
        "settings.gradle.kts",
        "build.gradle",
        "build.gradle.kts",
        ".git",
      ],
    },
  },
  {
    editorLanguageId: "lua",
    extensions: [".lua"],
    id: "lua",
    lsp: {
      binaryHint: "lua-language-server",
      command: "lua-language-server",
      displayName: "Lua",
      id: "lua-language-server",
      installCommand: "brew install lua-language-server",
      languageIds: ["lua"],
      priority: 70,
      rootMarkers: [".luarc.json", ".git"],
    },
  },
  {
    editorLanguageId: "php",
    extensions: [".php"],
    id: "php",
    lsp: {
      binaryHint: "intelephense",
      command: "intelephense",
      displayName: "PHP",
      id: "intelephense",
      installCommand: "npm i -g intelephense",
      languageIds: ["php"],
      priority: 70,
      rootMarkers: ["composer.json", ".git"],
    },
  },
  {
    editorLanguageId: "r",
    extensions: [".r", ".rmd"],
    id: "r",
    lsp: {
      args: ["--slave", "-e", "languageserver::run()"],
      binaryHint: "R",
      command: "R",
      displayName: "R",
      id: "r-languageserver",
      installCommand:
        'Install R from https://www.r-project.org, then in R: install.packages("languageserver")',
      languageIds: ["r"],
      priority: 70,
      rootMarkers: [".Rproj", "DESCRIPTION", ".git"],
    },
  },
  {
    editorLanguageId: "ruby",
    extensions: [".rb", ".rake", ".gemspec"],
    id: "ruby",
    lsp: {
      binaryHint: "ruby-lsp|solargraph",
      command: "ruby-lsp",
      displayName: "Ruby",
      id: "ruby-lsp",
      installCommand: "gem install ruby-lsp   # or: gem install solargraph",
      languageIds: ["ruby"],
      launchCandidates: [
        { args: [], command: "ruby-lsp" },
        { args: ["stdio"], command: "solargraph" },
      ],
      priority: 70,
      rootMarkers: ["Gemfile", ".ruby-version", ".git"],
    },
  },
  {
    editorLanguageId: "scala",
    extensions: [".scala", ".sc"],
    id: "scala",
    lsp: {
      binaryHint: "metals",
      command: "metals",
      displayName: "Scala",
      id: "metals",
      installCommand: "brew install coursier && cs install metals",
      languageIds: ["scala"],
      priority: 70,
      rootMarkers: ["build.sbt", "project/build.properties", ".git"],
    },
  },
  {
    editorLanguageId: "shell",
    extensions: [".sh", ".bash", ".zsh", ".fish", ".cmd", ".ps1"],
    id: "shell",
    lsp: {
      args: ["start"],
      binaryHint: "bash-language-server",
      command: "bash-language-server",
      displayName: "Shell",
      extensions: [".sh", ".bash", ".zsh"],
      id: "bash-language-server",
      installCommand: "npm i -g bash-language-server",
      languageIdByExtension: {
        ".bash": "shellscript",
        ".sh": "shellscript",
        ".zsh": "shellscript",
      },
      languageIds: ["shellscript", "shell", "bash", "zsh"],
      priority: 70,
      rootMarkers: [...GIT],
    },
  },
  {
    editorLanguageId: "sql",
    extensions: [".sql"],
    id: "sql",
    lsp: {
      binaryHint: "sql-language-server",
      command: "sql-language-server",
      displayName: "SQL",
      id: "sql-language-server",
      installCommand: "npm i -g sql-language-server",
      languageIds: ["sql"],
      priority: 70,
      rootMarkers: [...GIT],
    },
  },
  {
    editorLanguageId: "swift",
    extensions: [".swift"],
    id: "swift",
    lsp: {
      binaryHint: "sourcekit-lsp|xcrun",
      command: "sourcekit-lsp",
      displayName: "Swift",
      id: "sourcekit-lsp",
      installCommand:
        "Install Xcode Command Line Tools (xcode-select --install) so sourcekit-lsp works",
      languageIds: ["swift"],
      launchCandidates: [
        { args: [], command: "sourcekit-lsp" },
        { args: ["sourcekit-lsp"], command: "xcrun" },
      ],
      priority: 70,
      rootMarkers: ["Package.swift", ".git"],
    },
  },
  {
    editorLanguageId: "toml",
    extensions: [".toml"],
    id: "toml",
    lsp: {
      args: ["lsp", "stdio"],
      binaryHint: "taplo",
      command: "taplo",
      displayName: "TOML",
      id: "taplo",
      installCommand: "brew install taplo",
      languageIds: ["toml"],
      priority: 70,
      rootMarkers: [...GIT],
    },
  },
  {
    editorLanguageId: "zig",
    extensions: [".zig", ".zon"],
    id: "zig",
    lsp: {
      binaryHint: "zls",
      command: "zls",
      displayName: "Zig",
      id: "zls",
      installCommand: "brew install zls",
      languageIds: ["zig"],
      priority: 70,
      rootMarkers: ["build.zig", "build.zig.zon", ".git"],
    },
  },
  {
    editorLanguageId: "terraform",
    extensions: [".tf", ".tfvars", ".hcl"],
    id: "terraform",
    lsp: {
      args: ["serve"],
      binaryHint: "terraform-ls",
      command: "terraform-ls",
      displayName: "Terraform",
      extensions: [".tf", ".tfvars"],
      id: "terraform-ls",
      installCommand: "brew install terraform-ls",
      languageIdByExtension: {
        ".tf": "terraform",
        ".tfvars": "terraform-vars",
      },
      languageIds: ["terraform", "terraform-vars"],
      priority: 70,
      rootMarkers: [".terraform.lock.hcl", ".git"],
    },
  },
  // --- Display-only (no PATH LSP in matrix) ---
  {
    editorLanguageId: "xml",
    extensions: [".xml"],
    id: "xml",
  },
  {
    editorLanguageId: "svg",
    extensions: [".svg"],
    id: "svg",
  },
] as const;
