export {
  buildWindowDisplays,
  buildWindowDisplaysFromDrafts,
  buildWindowIdentityDraft,
  isDistinctQualifier,
  pathBasename,
  resolveWindowDisplayCopy,
  stableTabQualifierFromPanel,
  type WindowDisplay,
  type WindowDisplayCopy,
  type WindowDisplayIconKind,
  type WindowIdentityDraft,
  windowDisplayCopyForLocale,
  windowDisplayCopyFromI18n,
} from "@shared/window-display/index.ts";
