/**
 * Canonical `pier/canvas` named exports.
 * Keep in sync with `pierCanvasExports` (renderer) — unit tests enforce equality.
 *
 * Two kinds, because the compile-time stub wraps them differently:
 * - {@link PIER_CANVAS_COMPONENT_EXPORT_NAMES}: rendered via `createElement`.
 * - {@link PIER_CANVAS_VALUE_EXPORT_NAMES}: called straight through, so hooks
 *   keep their arguments and return value.
 *
 * Scope: general product primitives from `@pier/ui` + host layout
 * (Artboard/ArtboardStage/Frame/Row/Stack/Text).
 * Excludes domain UI (file-tree, diff-view, widgets), app chrome (command/menubar),
 * and host-owned modals (dialog/sheet).
 */
export const PIER_CANVAS_COMPONENT_EXPORT_NAMES = [
  "Accordion",
  "AccordionContent",
  "AccordionItem",
  "AccordionTrigger",
  "Alert",
  "AlertAction",
  "AlertDescription",
  "AlertTitle",
  "Artboard",
  "ArtboardStage",
  "AspectRatio",
  "Avatar",
  "AvatarBadge",
  "AvatarFallback",
  "AvatarGroup",
  "AvatarGroupCount",
  "AvatarImage",
  "Badge",
  "Breadcrumb",
  "BreadcrumbEllipsis",
  "BreadcrumbItem",
  "BreadcrumbLink",
  "BreadcrumbList",
  "BreadcrumbPage",
  "BreadcrumbSeparator",
  "Button",
  "Card",
  "CardContent",
  "CardDescription",
  "CardHeader",
  "CardTitle",
  "Checkbox",
  "Collapsible",
  "CollapsibleContent",
  "CollapsibleTrigger",
  "DataChart",
  "DocsShell",
  "DropdownMenu",
  "DropdownMenuCheckboxItem",
  "DropdownMenuContent",
  "DropdownMenuGroup",
  "DropdownMenuItem",
  "DropdownMenuLabel",
  "DropdownMenuPortal",
  "DropdownMenuRadioGroup",
  "DropdownMenuRadioItem",
  "DropdownMenuSeparator",
  "DropdownMenuShortcut",
  "DropdownMenuSub",
  "DropdownMenuSubContent",
  "DropdownMenuSubTrigger",
  "DropdownMenuTrigger",
  "Empty",
  "EmptyContent",
  "EmptyDescription",
  "EmptyHeader",
  "EmptyMedia",
  "EmptyTitle",
  "Field",
  "FieldContent",
  "FieldDescription",
  "FieldError",
  "FieldGroup",
  "FieldLabel",
  "FieldLegend",
  "FieldSeparator",
  "FieldSet",
  "FieldTitle",
  "Frame",
  "HoverCard",
  "HoverCardContent",
  "HoverCardTrigger",
  "Input",
  "InputGroup",
  "InputGroupAddon",
  "InputGroupButton",
  "InputGroupInput",
  "InputGroupText",
  "InputGroupTextarea",
  "Item",
  "ItemActions",
  "ItemContent",
  "ItemDescription",
  "ItemFooter",
  "ItemGroup",
  "ItemHeader",
  "ItemMedia",
  "ItemSeparator",
  "ItemTitle",
  "Kbd",
  "KbdGroup",
  "Label",
  "MermaidDiagram",
  "NodeGraph",
  "Pagination",
  "PaginationContent",
  "PaginationEllipsis",
  "PaginationItem",
  "PaginationLink",
  "PaginationNext",
  "PaginationPrevious",
  "Popover",
  "PopoverAnchor",
  "PopoverContent",
  "PopoverDescription",
  "PopoverHeader",
  "PopoverTitle",
  "PopoverTrigger",
  "Progress",
  "RadioGroup",
  "RadioGroupItem",
  "Row",
  "ScrollArea",
  "ScrollBar",
  "Select",
  "SelectContent",
  "SelectGroup",
  "SelectItem",
  "SelectLabel",
  "SelectScrollDownButton",
  "SelectScrollUpButton",
  "SelectSeparator",
  "SelectTrigger",
  "SelectValue",
  "Separator",
  "Skeleton",
  "Slider",
  "Spinner",
  "Stack",
  "StatusIcon",
  "Switch",
  "Table",
  "TableBody",
  "TableCaption",
  "TableCell",
  "TableFooter",
  "TableHead",
  "TableHeader",
  "TableRow",
  "Tabs",
  "TabsContent",
  "TabsList",
  "TabsTrigger",
  "Text",
  "Textarea",
  "Toggle",
  "ToggleGroup",
  "ToggleGroupItem",
  "Tooltip",
  "TooltipContent",
  "TooltipProvider",
  "TooltipTrigger",
] as const;

/**
 * Non-component exports: hooks and plain functions the host passes through.
 *
 * `useCanvasFile` lets a canvas read and write sibling files in its own
 * directory (e.g. saving a nearby `data.json`). It is deliberately not a
 * general file API: the host resolves the root and the directory, the canvas
 * only names a sibling.
 */
export const PIER_CANVAS_VALUE_EXPORT_NAMES = ["useCanvasFile"] as const;

export const PIER_CANVAS_EXPORT_NAMES = [
  ...PIER_CANVAS_COMPONENT_EXPORT_NAMES,
  ...PIER_CANVAS_VALUE_EXPORT_NAMES,
] as const;

export type PierCanvasComponentExportName =
  (typeof PIER_CANVAS_COMPONENT_EXPORT_NAMES)[number];

export type PierCanvasValueExportName =
  (typeof PIER_CANVAS_VALUE_EXPORT_NAMES)[number];

export type PierCanvasExportName = (typeof PIER_CANVAS_EXPORT_NAMES)[number];
