export type Locale = "zh-CN" | "en" | "ja" | "ko";

const zhCN = {
  filesCount: "{{count}} 文件",
  linesUnavailable: "部分文件较大，仅显示文件数",
  projects: "项目",
  localDirectories: "本机目录",
  directoryScenario: "非 GIT 目录",
  mainDirectory: "主目录",
  mainDirectoryShort: "主目录",
  tasks: "任务",
  openProject: "打开项目…",
  attention: "需要你处理",
  running: "运行中",
  idle: "空闲",
  unread: "完成未查看",
  emptyTitle: "还没有项目",
  emptyDescription: "打开项目，或从最近的项目继续。",
  recent: "最近",
  recentName: "pier",
  recentPath: "~/Projects/pier",
  loading: "正在打开 {{name}}…",
  loadFailed: "无法打开 {{name}}。请检查目录后重试。",
  loadFailedDescription: "目录现在打不开。检查路径后重试，或打开别的项目。",
  retry: "重试",
  normalScenario: "日常工作",
  emptyScenario: "首次打开",
  loadingScenario: "读取中",
  errorScenario: "读取失败",
  remoteScenario: "远程主机",
  scenario: "场景",
  width: "侧栏宽度",
  located: "已定位到 {{name}}",
  switched: "已切换到 {{name}}",
  previewOnly: "交互设计稿，使用示例数据。",
  keyboardHelp:
    "方向键在任务、项目、工作树、会话和最近项目之间移动。Home 和 End 到首尾。Esc 退出任务或取消定位。Option+↓ 跳到下一条需要你处理。左右键展开或收起项目。",
  actionPreview: "操作预览",
  newWorktreeFor: "在 {{name}} 新建工作树",
  sidebarToggle: "显示或隐藏侧栏",
  sidebar: "侧栏",
  language: "语言",
  collapsedProject: "已收起 {{name}}",
  expandedProject: "已展开 {{name}}",
  sshHost: "SSH · {{host}}",
  clearedLocate: "已取消会话定位",
  leftTasks: "已离开任务",
  otherWindow: "其他窗口",
  currentHere: "本窗口当前",
  peekGitDelta: "增删摘要",
  peekGitFiles: "仅文件数",
  branch: "分支",
} as const;

export type Copy = { [Key in keyof typeof zhCN]: string };

export const COPY: Record<Locale, Copy> = {
  "zh-CN": zhCN,
  en: {
    filesCount: "{{count}} files",
    linesUnavailable: "Some files are large; showing file count only",
    projects: "Projects",
    localDirectories: "Local directories",
    directoryScenario: "Non-GIT directory",
    mainDirectory: "Main directory",
    mainDirectoryShort: "Main",
    tasks: "Tasks",
    openProject: "Open project…",
    attention: "Needs your attention",
    running: "Running",
    idle: "Idle",
    unread: "Finished, unread",
    emptyTitle: "No projects yet",
    emptyDescription: "Open a project or continue with a recent one.",
    recent: "Recent",
    recentName: "pier",
    recentPath: "~/Projects/pier",
    loading: "Opening {{name}}…",
    loadFailed: "Could not open {{name}}. Check the directory and try again.",
    loadFailedDescription:
      "This directory cannot be opened right now. Check the path and try again, or open another project.",
    retry: "Try again",
    normalScenario: "Everyday work",
    emptyScenario: "First launch",
    loadingScenario: "Loading",
    errorScenario: "Loading failed",
    remoteScenario: "Remote host",
    scenario: "Scenario",
    width: "Sidebar width",
    located: "Located {{name}}",
    switched: "Switched to {{name}}",
    previewOnly: "Interactive design using sample data.",
    keyboardHelp:
      "Arrow keys move through Tasks, projects, worktrees, sessions, and Recents. Home and End jump to the ends. Esc leaves Tasks or clears a location. Option-Down jumps to the next session that needs you. Left or Right collapse or expand a project.",
    actionPreview: "Action preview",
    newWorktreeFor: "Create a worktree in {{name}}",
    sidebarToggle: "Show or hide sidebar",
    sidebar: "Sidebar",
    language: "Language",
    collapsedProject: "Collapsed {{name}}",
    expandedProject: "Expanded {{name}}",
    sshHost: "SSH · {{host}}",
    clearedLocate: "Cleared session location",
    leftTasks: "Left Tasks",
    otherWindow: "Other window",
    currentHere: "Current in this window",
    peekGitDelta: "Add/delete summary",
    peekGitFiles: "File count only",
    branch: "Branch",
  },
  ja: {
    filesCount: "{{count}} 件",
    linesUnavailable: "大きなファイルがあるため、ファイル数のみ表示",
    projects: "プロジェクト",
    localDirectories: "ローカルディレクトリ",
    directoryScenario: "GIT 管理外のディレクトリ",
    mainDirectory: "メインディレクトリ",
    mainDirectoryShort: "メイン",
    tasks: "タスク",
    openProject: "プロジェクトを開く…",
    attention: "対応が必要",
    running: "実行中",
    idle: "待機中",
    unread: "完了・未確認",
    emptyTitle: "プロジェクトはまだありません",
    emptyDescription:
      "プロジェクトを開くか、最近使ったプロジェクトから再開できます。",
    recent: "最近使った項目",
    recentName: "pier",
    recentPath: "~/Projects/pier",
    loading: "{{name}} を開いています…",
    loadFailed:
      "{{name}} を開けませんでした。ディレクトリを確認して再試行してください。",
    loadFailedDescription:
      "このディレクトリは今開けません。パスを確認して再試行するか、別のプロジェクトを開いてください。",
    retry: "再試行",
    normalScenario: "通常の作業",
    emptyScenario: "初回起動",
    loadingScenario: "読み込み中",
    errorScenario: "読み込み失敗",
    remoteScenario: "リモートホスト",
    scenario: "シナリオ",
    width: "サイドバーの幅",
    located: "{{name}} を表示しました",
    switched: "{{name}} に切り替えました",
    previewOnly: "サンプルデータを使った操作可能なデザインです。",
    keyboardHelp:
      "矢印キーでタスク、プロジェクト、ワークツリー、セッション、最近使った項目を移動します。Home と End で先頭と末尾に移動します。Esc でタスクを離れるか位置指定を解除します。Option+↓ で次の対応が必要なセッションに移動します。左右キーでプロジェクトを展開・折りたたみます。",
    actionPreview: "操作のプレビュー",
    newWorktreeFor: "{{name}} にワークツリーを作成",
    sidebarToggle: "サイドバーの表示を切り替える",
    sidebar: "サイドバー",
    language: "言語",
    collapsedProject: "{{name}} を折りたたみました",
    expandedProject: "{{name}} を展開しました",
    sshHost: "SSH · {{host}}",
    clearedLocate: "セッションの位置指定を解除しました",
    leftTasks: "タスクを離れました",
    otherWindow: "別ウィンドウ",
    currentHere: "このウィンドウで表示中",
    peekGitDelta: "追加と削除",
    peekGitFiles: "ファイル数のみ",
    branch: "ブランチ",
  },
  ko: {
    filesCount: "{{count}}개",
    linesUnavailable: "일부 파일이 커서 파일 수만 표시합니다",
    projects: "프로젝트",
    localDirectories: "로컬 디렉터리",
    directoryScenario: "GIT 외 디렉터리",
    mainDirectory: "기본 디렉터리",
    mainDirectoryShort: "기본",
    tasks: "작업",
    openProject: "프로젝트 열기…",
    attention: "확인이 필요함",
    running: "실행 중",
    idle: "대기 중",
    unread: "완료 · 읽지 않음",
    emptyTitle: "아직 프로젝트가 없습니다",
    emptyDescription: "프로젝트를 열거나 최근 프로젝트에서 계속하세요.",
    recent: "최근 항목",
    recentName: "pier",
    recentPath: "~/Projects/pier",
    loading: "{{name}} 여는 중…",
    loadFailed:
      "{{name}}을(를) 열 수 없습니다. 디렉터리를 확인한 후 다시 시도하세요.",
    loadFailedDescription:
      "지금 이 디렉터리를 열 수 없습니다. 경로를 확인한 뒤 다시 시도하거나 다른 프로젝트를 여세요.",
    retry: "다시 시도",
    normalScenario: "일상 작업",
    emptyScenario: "첫 실행",
    loadingScenario: "불러오는 중",
    errorScenario: "불러오기 실패",
    remoteScenario: "원격 호스트",
    scenario: "시나리오",
    width: "사이드바 너비",
    located: "{{name}}을(를) 표시했습니다",
    switched: "{{name}}(으)로 전환했습니다",
    previewOnly: "예시 데이터를 사용하는 인터랙션 디자인입니다.",
    keyboardHelp:
      "방향키로 작업, 프로젝트, 작업 트리, 세션, 최근 항목을 이동합니다. Home과 End로 처음과 끝으로 이동합니다. Esc로 작업을 떠나거나 위치 지정을 취소합니다. Option+↓로 다음 확인이 필요한 세션으로 이동합니다. 좌우 방향키로 프로젝트를 접거나 펼칩니다.",
    actionPreview: "작업 미리보기",
    newWorktreeFor: "{{name}}에 작업 트리 만들기",
    sidebarToggle: "사이드바 표시 전환",
    sidebar: "사이드바",
    language: "언어",
    collapsedProject: "{{name}}을(를) 접었습니다",
    expandedProject: "{{name}}을(를) 펼쳤습니다",
    sshHost: "SSH · {{host}}",
    clearedLocate: "세션 위치 지정을 취소했습니다",
    leftTasks: "작업을 떠났습니다",
    otherWindow: "다른 창",
    currentHere: "이 창에서 보는 중",
    peekGitDelta: "추가/삭제 요약",
    peekGitFiles: "파일 수만",
    branch: "브랜치",
  },
};
