export const PIER_FILE_ICON_COLOR_BY_TOKEN: Readonly<Record<string, string>> = {
  astro: "var(--pier-file-icon-purple)",
  babel: "var(--pier-file-icon-yellow)",
  bash: "var(--pier-file-icon-green)",
  biome: "var(--pier-file-icon-blue)",
  bootstrap: "var(--pier-file-icon-indigo)",
  browserslist: "var(--pier-file-icon-yellow)",
  bun: "var(--pier-file-icon-mauve)",
  c: "var(--pier-file-icon-blue)",
  canvas: "var(--pier-file-icon-indigo)",
  claude: "var(--pier-file-icon-orange)",
  cpp: "var(--pier-file-icon-blue)",
  csharp: "var(--pier-file-icon-purple)",
  css: "var(--pier-file-icon-indigo)",
  dart: "var(--pier-file-icon-teal)",
  database: "var(--pier-file-icon-purple)",
  default: "var(--pier-file-icon-gray)",
  docker: "var(--pier-file-icon-blue)",
  elixir: "var(--pier-file-icon-purple)",
  eslint: "var(--pier-file-icon-indigo)",
  font: "var(--pier-file-icon-gray)",
  git: "var(--pier-file-icon-vermilion)",
  go: "var(--pier-file-icon-cyan)",
  graphql: "var(--pier-file-icon-pink)",
  html: "var(--pier-file-icon-orange)",
  image: "var(--pier-file-icon-pink)",
  java: "var(--pier-file-icon-orange)",
  javascript: "var(--pier-file-icon-yellow)",
  json: "var(--pier-file-icon-orange)",
  kotlin: "var(--pier-file-icon-indigo)",
  lua: "var(--pier-file-icon-blue)",
  markdown: "var(--pier-file-icon-green)",
  mcp: "var(--pier-file-icon-teal)",
  nextjs: "var(--pier-file-icon-gray)",
  npm: "var(--pier-file-icon-red)",
  oxc: "var(--pier-file-icon-cyan)",
  php: "var(--pier-file-icon-indigo)",
  postcss: "var(--pier-file-icon-red)",
  prettier: "var(--pier-file-icon-teal)",
  python: "var(--pier-file-icon-blue)",
  r: "var(--pier-file-icon-blue)",
  react: "var(--pier-file-icon-cyan)",
  ruby: "var(--pier-file-icon-red)",
  rust: "var(--pier-file-icon-orange)",
  sass: "var(--pier-file-icon-pink)",
  scala: "var(--pier-file-icon-red)",
  stylelint: "var(--pier-file-icon-gray)",
  svelte: "var(--pier-file-icon-red)",
  svg: "var(--pier-file-icon-orange)",
  svgo: "var(--pier-file-icon-green)",
  swift: "var(--pier-file-icon-orange)",
  table: "var(--pier-file-icon-teal)",
  tailwind: "var(--pier-file-icon-cyan)",
  terraform: "var(--pier-file-icon-indigo)",
  text: "var(--pier-file-icon-gray)",
  toml: "var(--pier-file-icon-orange)",
  typescript: "var(--pier-file-icon-blue)",
  vite: "var(--pier-file-icon-purple)",
  vscode: "var(--pier-file-icon-blue)",
  vue: "var(--pier-file-icon-green)",
  wasm: "var(--pier-file-icon-indigo)",
  webpack: "var(--pier-file-icon-blue)",
  xml: "var(--pier-file-icon-orange)",
  yml: "var(--pier-file-icon-red)",
  zig: "var(--pier-file-icon-orange)",
  zip: "var(--pier-file-icon-orange)",
};

export const PIER_FILE_TREE_ICON_COLOR_OVERRIDES: Readonly<
  Record<`--trees-file-icon-color-${string}`, string>
> = Object.fromEntries(
  Object.entries(PIER_FILE_ICON_COLOR_BY_TOKEN).map(([token, color]) => [
    `--trees-file-icon-color-${token}`,
    color,
  ])
);
