import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { AGENT_CATALOG } from "@shared/agent-catalog.ts";

/**
 * zsh 命令上报注入（loomdesk shell-integration/v1 的 ZDOTDIR 包装移植,
 * 去 OSC 部分——Pier 无 PTY 流解析, 命令行改 POST 给 agent hook loopback）。
 *
 * 机制：PTY env 注入 `ZDOTDIR=<wrapper>` + `USER_ZDOTDIR=<用户原值>`。
 * ghostty 自身 shell integration 与此正交（它经自己的 .zshenv 还原并链回
 * 本 wrapper）。wrapper 四件套逐个 source 用户真实 rc, preexec 上报命令行。
 * 覆盖范围 zsh-only（macOS 默认 shell）; bash/fish 忽略 ZDOTDIR, 无副作用,
 * 身份退化为 hook/launch/标题兜底。
 */

const FILE_HEADER =
  "# Generated by Pier — do not edit; regenerated at startup.";

const TOKEN_ID_RE = /^[a-z0-9-]+$/;

const ZSHENV = `${FILE_HEADER}
# Pier zsh shell integration — .zshenv
#
# source 用户 .zshenv 时临时切回 USER_ZDOTDIR, 让用户在 .zshenv 内迁移
# ZDOTDIR 的配置生效; source 后采纳新的用户 ZDOTDIR, 再恢复 Pier ZDOTDIR,
# 确保后续仍加载 Pier .zshrc 注入 preexec。\`\${VAR:-}\` 防 nounset。
_PIER_OWN_ZDOTDIR="\${ZDOTDIR:-}"
if [ -n "\${USER_ZDOTDIR:-}" ] && [ -f "\${USER_ZDOTDIR}/.zshenv" ]; then
	export ZDOTDIR="$USER_ZDOTDIR"
	if [ "\${USER_ZDOTDIR:-}" != "\${_PIER_OWN_ZDOTDIR:-}" ]; then
		source "\${USER_ZDOTDIR}/.zshenv"
	fi
	export USER_ZDOTDIR="\${ZDOTDIR:-$USER_ZDOTDIR}"
fi
if [ -n "\${_PIER_OWN_ZDOTDIR:-}" ]; then
	export ZDOTDIR="$_PIER_OWN_ZDOTDIR"
fi
unset _PIER_OWN_ZDOTDIR
`;

const ZPROFILE = `${FILE_HEADER}
# Pier zsh shell integration — .zprofile (login shell)
#
# 顶部切 ZDOTDIR=USER_ZDOTDIR 给用户 .zprofile 内的 framework init
# (nvm/asdf/direnv/starship) 看到真实路径; source 后必须切回, 否则后续
# 读用户 ZDOTDIR 的 .zshrc, Pier 注入不会被 source。
_PIER_OWN_ZDOTDIR="\${ZDOTDIR:-}"
if [ -n "\${USER_ZDOTDIR:-}" ]; then
	export ZDOTDIR="$USER_ZDOTDIR"
fi
[ -n "\${USER_ZDOTDIR:-}" ] && [ -f "\${USER_ZDOTDIR}/.zprofile" ] && source "\${USER_ZDOTDIR}/.zprofile"
if [ -n "\${_PIER_OWN_ZDOTDIR:-}" ]; then
	export ZDOTDIR="$_PIER_OWN_ZDOTDIR"
fi
unset _PIER_OWN_ZDOTDIR
`;

const ZLOGIN = `${FILE_HEADER}
# Pier zsh shell integration — .zlogin (login shell)
[ -n "\${USER_ZDOTDIR:-}" ] && [ -f "\${USER_ZDOTDIR}/.zlogin" ] && source "\${USER_ZDOTDIR}/.zlogin"
`;

/**
 * preexec 客户端预过滤 glob：命令行含任一 agent 词元子串才 POST——
 * ls/git 等高频命令零开销（精确词元匹配在 main 侧完成）。
 */
function agentTokenGlobs(): string {
  const tokens = new Set<string>();
  for (const entry of AGENT_CATALOG) {
    tokens.add(entry.id.toLowerCase());
    tokens.add(entry.detectCmd.toLowerCase());
    for (const alias of entry.detectCmdAliases ?? []) {
      tokens.add(alias.toLowerCase());
    }
    tokens.add(entry.expectedProcess.toLowerCase());
    const launchWord = entry.launchCmd.split(" ")[0];
    if (launchWord) {
      tokens.add(launchWord.toLowerCase());
    }
  }
  return [...tokens]
    .filter((token) => TOKEN_ID_RE.test(token))
    .sort()
    .map((token) => `*${token}*`)
    .join("|");
}

function buildZshrc(): string {
  return `${FILE_HEADER}
# Pier zsh shell integration — .zshrc
#
# 职责：1) 链回用户真实 .zshrc; 2) preexec 把命令行 POST 给 Pier loopback
# (agent 身份先验探测, loomdesk OSC 633;E 的 HTTP 版)。

# idempotent guard — 用户误 source 本文件时 hook 幂等。
[[ -n "\${PIER_ZSH_LOADED:-}" ]] && return 0
PIER_ZSH_LOADED=1
typeset +x PIER_ZSH_LOADED 2>/dev/null || true

# HISTFILE 钉死到用户主目录 — 防 ZDOTDIR swap 让 zsh 把 HISTFILE 默认指到
# Pier 目录, 跨终端 history 互不可见（macOS /etc/zshrc 按 ZDOTDIR 重设）。
HISTFILE="\${USER_ZDOTDIR:-$HOME}/.zsh_history"
export HISTFILE

if [ -n "\${USER_ZDOTDIR:-}" ] && [ -f "\${USER_ZDOTDIR}/.zshrc" ]; then
	# source 用户 .zshrc 期间临时切 ZDOTDIR 回真实值 — framework
	# (oh-my-zsh/starship) 常按 ZDOTDIR 定位 HISTFILE 与 cache。
	_PIER_OWN_ZDOTDIR="$ZDOTDIR"
	export ZDOTDIR="$USER_ZDOTDIR"
	source "\${USER_ZDOTDIR}/.zshrc"
	export ZDOTDIR="$_PIER_OWN_ZDOTDIR"
	unset _PIER_OWN_ZDOTDIR
fi

autoload -Uz add-zsh-hook

# 前台命令开始上报：headers 走路由字段, raw body 走命令行（免 JSON 转义）。
# curl 背景化 + disown, 不阻塞 prompt; -m 2 兜底; 输出全丢。
__pier_report_command() {
	[[ -n "\${PIER_AGENT_HOOK_PORT:-}" && -n "\${PIER_AGENT_HOOK_TOKEN:-}" && -n "\${PIER_PANEL_ID:-}" && -n "\${PIER_WINDOW_ID:-}" ]] || return 0
	case "\${(L)1}" in
	(${agentTokenGlobs()})
		print -rn -- "\${1[1,4096]}" | command curl -fsS -m 2 -X POST \\
			"http://127.0.0.1:$PIER_AGENT_HOOK_PORT/command-event" \\
			-H "Authorization: Bearer $PIER_AGENT_HOOK_TOKEN" \\
			-H "X-Pier-Panel-Id: $PIER_PANEL_ID" \\
			-H "X-Pier-Window-Id: $PIER_WINDOW_ID" \\
			-H "Content-Type: text/plain" \\
			--data-binary @- >/dev/null 2>&1 &!
		;;
	esac
	return 0
}
add-zsh-hook preexec __pier_report_command

# 末尾恢复 ZDOTDIR 给后续工具(starship/p10k 等)看到真实值。
if [ -n "\${USER_ZDOTDIR:-}" ]; then
	export ZDOTDIR="$USER_ZDOTDIR"
fi
`;
}

export function shellIntegrationZshDir(baseDir: string): string {
  return join(baseDir, "shell-integration", "zsh");
}

/** 幂等写入 wrapper 四件套（内容随 app 版本演进, 每次启动覆盖）。 */
export async function installShellCommandIntegration(
  baseDir: string
): Promise<void> {
  const dir = shellIntegrationZshDir(baseDir);
  await mkdir(dir, { recursive: true });
  await Promise.all([
    writeFile(join(dir, ".zshenv"), ZSHENV, "utf8"),
    writeFile(join(dir, ".zprofile"), ZPROFILE, "utf8"),
    writeFile(join(dir, ".zshrc"), buildZshrc(), "utf8"),
    writeFile(join(dir, ".zlogin"), ZLOGIN, "utf8"),
  ]);
}

/**
 * PTY 注入 env：ZDOTDIR 指向 wrapper, USER_ZDOTDIR 传递用户原值
 * （Electron GUI 进程几乎不带 ZDOTDIR, 兜底 $HOME; 用户在自己 .zshenv 里
 * 迁移 ZDOTDIR 的场景由 wrapper .zshenv 采纳）。
 */
export function shellCommandIntegrationEnv(
  baseDir: string
): Record<string, string> {
  return {
    USER_ZDOTDIR: process.env.ZDOTDIR ?? homedir(),
    ZDOTDIR: shellIntegrationZshDir(baseDir),
  };
}
