import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  installShellCommandIntegration,
  shellCommandIntegrationEnv,
  shellIntegrationZshDir,
} from "../../src/main/services/agents/shell-command-integration.ts";

describe("shell-command-integration", () => {
  let baseDir: string | null = null;

  afterEach(async () => {
    if (baseDir) {
      await rm(baseDir, { force: true, recursive: true });
      baseDir = null;
    }
  });

  it("install 写入 wrapper 四件套且 .zshrc 含 preexec 上报", async () => {
    baseDir = await mkdtemp(join(tmpdir(), "pier-shell-int-"));
    await installShellCommandIntegration(baseDir);
    const dir = shellIntegrationZshDir(baseDir);

    const zshrc = await readFile(join(dir, ".zshrc"), "utf8");
    expect(zshrc).toContain("add-zsh-hook preexec __pier_report_command");
    expect(zshrc).toContain("/command-event");
    expect(zshrc).toContain("X-Pier-Panel-Id");
    // 客户端预过滤 glob 由 catalog 派生
    expect(zshrc).toContain("*codex*");
    expect(zshrc).toContain("*claude*");
    // 链回用户真实 rc + HISTFILE 钉死
    expect(zshrc).toContain(`source "\${USER_ZDOTDIR}/.zshrc"`);
    expect(zshrc).toContain(`HISTFILE="\${USER_ZDOTDIR:-$HOME}/.zsh_history"`);

    const zshenv = await readFile(join(dir, ".zshenv"), "utf8");
    expect(zshenv).toContain(`source "\${USER_ZDOTDIR}/.zshenv"`);
    const zprofile = await readFile(join(dir, ".zprofile"), "utf8");
    expect(zprofile).toContain(`source "\${USER_ZDOTDIR}/.zprofile"`);
    const zlogin = await readFile(join(dir, ".zlogin"), "utf8");
    expect(zlogin).toContain(`source "\${USER_ZDOTDIR}/.zlogin"`);
  });

  it("install 幂等（重复调用覆盖写入不抛错）", async () => {
    baseDir = await mkdtemp(join(tmpdir(), "pier-shell-int-"));
    await installShellCommandIntegration(baseDir);
    await installShellCommandIntegration(baseDir);
    const zshrc = await readFile(
      join(shellIntegrationZshDir(baseDir), ".zshrc"),
      "utf8"
    );
    expect(zshrc).toContain("Generated by Pier");
  });

  it("env 指向 wrapper 目录, USER_ZDOTDIR 兜底用户主目录", () => {
    const env = shellCommandIntegrationEnv("/base");
    expect(env.ZDOTDIR).toBe(join("/base", "shell-integration", "zsh"));
    expect(env.USER_ZDOTDIR).toBeTruthy();
  });
});
